/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Promotion202309UpdateActivityRequestBodyTargetUserInfo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Promotion202309UpdateActivityRequestBodyTargetUserInfo{}

// Promotion202309UpdateActivityRequestBodyTargetUserInfo struct for Promotion202309UpdateActivityRequestBodyTargetUserInfo
type Promotion202309UpdateActivityRequestBodyTargetUserInfo struct {
    // Possible enumerations are: `ALL_USER` `SHOP_NEW_CUSTOMER` `SHOP_EXISTING_CUSTOMER` `SHOP_REPEAT_CUSTOMER`
    UserType *string `json:"user_type,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Promotion202309UpdateActivityRequestBodyTargetUserInfo Promotion202309UpdateActivityRequestBodyTargetUserInfo

// NewPromotion202309UpdateActivityRequestBodyTargetUserInfo instantiates a new Promotion202309UpdateActivityRequestBodyTargetUserInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotion202309UpdateActivityRequestBodyTargetUserInfo() *Promotion202309UpdateActivityRequestBodyTargetUserInfo {
    this := Promotion202309UpdateActivityRequestBodyTargetUserInfo{}
    return &this
}

// NewPromotion202309UpdateActivityRequestBodyTargetUserInfoWithDefaults instantiates a new Promotion202309UpdateActivityRequestBodyTargetUserInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotion202309UpdateActivityRequestBodyTargetUserInfoWithDefaults() *Promotion202309UpdateActivityRequestBodyTargetUserInfo {
    this := Promotion202309UpdateActivityRequestBodyTargetUserInfo{}
    return &this
}

// GetUserType returns the UserType field value if set, zero value otherwise.
func (o *Promotion202309UpdateActivityRequestBodyTargetUserInfo) GetUserType() string {
    if o == nil || utils.IsNil(o.UserType) {
        var ret string
        return ret
    }
    return *o.UserType
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309UpdateActivityRequestBodyTargetUserInfo) GetUserTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.UserType) {
        return nil, false
    }
    return o.UserType, true
}

// HasUserType returns a boolean if a field has been set.
func (o *Promotion202309UpdateActivityRequestBodyTargetUserInfo) HasUserType() bool {
    if o != nil && !utils.IsNil(o.UserType) {
        return true
    }

    return false
}

// SetUserType gets a reference to the given string and assigns it to the UserType field.
func (o *Promotion202309UpdateActivityRequestBodyTargetUserInfo) SetUserType(v string) {
    o.UserType = &v
}

func (o Promotion202309UpdateActivityRequestBodyTargetUserInfo) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Promotion202309UpdateActivityRequestBodyTargetUserInfo) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.UserType) {
        toSerialize["user_type"] = o.UserType
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Promotion202309UpdateActivityRequestBodyTargetUserInfo) UnmarshalJSON(data []byte) (err error) {
    varPromotion202309UpdateActivityRequestBodyTargetUserInfo := _Promotion202309UpdateActivityRequestBodyTargetUserInfo{}

    err = json.Unmarshal(data, &varPromotion202309UpdateActivityRequestBodyTargetUserInfo)

    if err != nil {
        return err
    }

    *o = Promotion202309UpdateActivityRequestBodyTargetUserInfo(varPromotion202309UpdateActivityRequestBodyTargetUserInfo)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "user_type")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo struct {
	value *Promotion202309UpdateActivityRequestBodyTargetUserInfo
	isSet bool
}

func (v NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) Get() *Promotion202309UpdateActivityRequestBodyTargetUserInfo {
	return v.value
}

func (v *NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) Set(val *Promotion202309UpdateActivityRequestBodyTargetUserInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotion202309UpdateActivityRequestBodyTargetUserInfo(val *Promotion202309UpdateActivityRequestBodyTargetUserInfo) *NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo {
	return &NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo{value: val, isSet: true}
}

func (v NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotion202309UpdateActivityRequestBodyTargetUserInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


