/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Analytics202509GetShopProductPerformanceListResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Analytics202509GetShopProductPerformanceListResponse{}

// Analytics202509GetShopProductPerformanceListResponse struct for Analytics202509GetShopProductPerformanceListResponse
type Analytics202509GetShopProductPerformanceListResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data *Analytics202509GetShopProductPerformanceListResponseData `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Analytics202509GetShopProductPerformanceListResponse Analytics202509GetShopProductPerformanceListResponse

// NewAnalytics202509GetShopProductPerformanceListResponse instantiates a new Analytics202509GetShopProductPerformanceListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalytics202509GetShopProductPerformanceListResponse() *Analytics202509GetShopProductPerformanceListResponse {
    this := Analytics202509GetShopProductPerformanceListResponse{}
    return &this
}

// NewAnalytics202509GetShopProductPerformanceListResponseWithDefaults instantiates a new Analytics202509GetShopProductPerformanceListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalytics202509GetShopProductPerformanceListResponseWithDefaults() *Analytics202509GetShopProductPerformanceListResponse {
    this := Analytics202509GetShopProductPerformanceListResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *Analytics202509GetShopProductPerformanceListResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetData() Analytics202509GetShopProductPerformanceListResponseData {
    if o == nil || utils.IsNil(o.Data) {
        var ret Analytics202509GetShopProductPerformanceListResponseData
        return ret
    }
    return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetDataOk() (*Analytics202509GetShopProductPerformanceListResponseData, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return nil, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given Analytics202509GetShopProductPerformanceListResponseData and assigns it to the Data field.
func (o *Analytics202509GetShopProductPerformanceListResponse) SetData(v Analytics202509GetShopProductPerformanceListResponseData) {
    o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Analytics202509GetShopProductPerformanceListResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *Analytics202509GetShopProductPerformanceListResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o Analytics202509GetShopProductPerformanceListResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Analytics202509GetShopProductPerformanceListResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Analytics202509GetShopProductPerformanceListResponse) UnmarshalJSON(data []byte) (err error) {
    varAnalytics202509GetShopProductPerformanceListResponse := _Analytics202509GetShopProductPerformanceListResponse{}

    err = json.Unmarshal(data, &varAnalytics202509GetShopProductPerformanceListResponse)

    if err != nil {
        return err
    }

    *o = Analytics202509GetShopProductPerformanceListResponse(varAnalytics202509GetShopProductPerformanceListResponse)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "code")
        delete(additionalProperties, "data")
        delete(additionalProperties, "message")
        delete(additionalProperties, "request_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAnalytics202509GetShopProductPerformanceListResponse struct {
	value *Analytics202509GetShopProductPerformanceListResponse
	isSet bool
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponse) Get() *Analytics202509GetShopProductPerformanceListResponse {
	return v.value
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponse) Set(val *Analytics202509GetShopProductPerformanceListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalytics202509GetShopProductPerformanceListResponse(val *Analytics202509GetShopProductPerformanceListResponse) *NullableAnalytics202509GetShopProductPerformanceListResponse {
	return &NullableAnalytics202509GetShopProductPerformanceListResponse{value: val, isSet: true}
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


