/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Analytics202509GetShopVideoPerformanceListResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Analytics202509GetShopVideoPerformanceListResponseData{}

// Analytics202509GetShopVideoPerformanceListResponseData struct for Analytics202509GetShopVideoPerformanceListResponseData
type Analytics202509GetShopVideoPerformanceListResponseData struct {
    // Latest date in local timezone where data is ready (ISO 8601 format).
    LatestAvailableDate *string `json:"latest_available_date,omitempty"`
    // Page token for the next page request.
    NextPageToken *string `json:"next_page_token,omitempty"`
    // Total number of videos.
    TotalCount *int64 `json:"total_count,omitempty"`
    // List of video performance metrics.
    Videos []Analytics202509GetShopVideoPerformanceListResponseDataVideos `json:"videos,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Analytics202509GetShopVideoPerformanceListResponseData Analytics202509GetShopVideoPerformanceListResponseData

// NewAnalytics202509GetShopVideoPerformanceListResponseData instantiates a new Analytics202509GetShopVideoPerformanceListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalytics202509GetShopVideoPerformanceListResponseData() *Analytics202509GetShopVideoPerformanceListResponseData {
    this := Analytics202509GetShopVideoPerformanceListResponseData{}
    return &this
}

// NewAnalytics202509GetShopVideoPerformanceListResponseDataWithDefaults instantiates a new Analytics202509GetShopVideoPerformanceListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalytics202509GetShopVideoPerformanceListResponseDataWithDefaults() *Analytics202509GetShopVideoPerformanceListResponseData {
    this := Analytics202509GetShopVideoPerformanceListResponseData{}
    return &this
}

// GetLatestAvailableDate returns the LatestAvailableDate field value if set, zero value otherwise.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetLatestAvailableDate() string {
    if o == nil || utils.IsNil(o.LatestAvailableDate) {
        var ret string
        return ret
    }
    return *o.LatestAvailableDate
}

// GetLatestAvailableDateOk returns a tuple with the LatestAvailableDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetLatestAvailableDateOk() (*string, bool) {
    if o == nil || utils.IsNil(o.LatestAvailableDate) {
        return nil, false
    }
    return o.LatestAvailableDate, true
}

// HasLatestAvailableDate returns a boolean if a field has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) HasLatestAvailableDate() bool {
    if o != nil && !utils.IsNil(o.LatestAvailableDate) {
        return true
    }

    return false
}

// SetLatestAvailableDate gets a reference to the given string and assigns it to the LatestAvailableDate field.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) SetLatestAvailableDate(v string) {
    o.LatestAvailableDate = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetTotalCount() int64 {
    if o == nil || utils.IsNil(o.TotalCount) {
        var ret int64
        return ret
    }
    return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetTotalCountOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TotalCount) {
        return nil, false
    }
    return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) HasTotalCount() bool {
    if o != nil && !utils.IsNil(o.TotalCount) {
        return true
    }

    return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) SetTotalCount(v int64) {
    o.TotalCount = &v
}

// GetVideos returns the Videos field value if set, zero value otherwise.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetVideos() []Analytics202509GetShopVideoPerformanceListResponseDataVideos {
    if o == nil || utils.IsNil(o.Videos) {
        var ret []Analytics202509GetShopVideoPerformanceListResponseDataVideos
        return ret
    }
    return o.Videos
}

// GetVideosOk returns a tuple with the Videos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) GetVideosOk() ([]Analytics202509GetShopVideoPerformanceListResponseDataVideos, bool) {
    if o == nil || utils.IsNil(o.Videos) {
        return nil, false
    }
    return o.Videos, true
}

// HasVideos returns a boolean if a field has been set.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) HasVideos() bool {
    if o != nil && !utils.IsNil(o.Videos) {
        return true
    }

    return false
}

// SetVideos gets a reference to the given []Analytics202509GetShopVideoPerformanceListResponseDataVideos and assigns it to the Videos field.
func (o *Analytics202509GetShopVideoPerformanceListResponseData) SetVideos(v []Analytics202509GetShopVideoPerformanceListResponseDataVideos) {
    o.Videos = v
}

func (o Analytics202509GetShopVideoPerformanceListResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Analytics202509GetShopVideoPerformanceListResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.LatestAvailableDate) {
        toSerialize["latest_available_date"] = o.LatestAvailableDate
    }
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.TotalCount) {
        toSerialize["total_count"] = o.TotalCount
    }
    if !utils.IsNil(o.Videos) {
        toSerialize["videos"] = o.Videos
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Analytics202509GetShopVideoPerformanceListResponseData) UnmarshalJSON(data []byte) (err error) {
    varAnalytics202509GetShopVideoPerformanceListResponseData := _Analytics202509GetShopVideoPerformanceListResponseData{}

    err = json.Unmarshal(data, &varAnalytics202509GetShopVideoPerformanceListResponseData)

    if err != nil {
        return err
    }

    *o = Analytics202509GetShopVideoPerformanceListResponseData(varAnalytics202509GetShopVideoPerformanceListResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "latest_available_date")
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "total_count")
        delete(additionalProperties, "videos")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAnalytics202509GetShopVideoPerformanceListResponseData struct {
	value *Analytics202509GetShopVideoPerformanceListResponseData
	isSet bool
}

func (v NullableAnalytics202509GetShopVideoPerformanceListResponseData) Get() *Analytics202509GetShopVideoPerformanceListResponseData {
	return v.value
}

func (v *NullableAnalytics202509GetShopVideoPerformanceListResponseData) Set(val *Analytics202509GetShopVideoPerformanceListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalytics202509GetShopVideoPerformanceListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalytics202509GetShopVideoPerformanceListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalytics202509GetShopVideoPerformanceListResponseData(val *Analytics202509GetShopVideoPerformanceListResponseData) *NullableAnalytics202509GetShopVideoPerformanceListResponseData {
	return &NullableAnalytics202509GetShopVideoPerformanceListResponseData{value: val, isSet: true}
}

func (v NullableAnalytics202509GetShopVideoPerformanceListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalytics202509GetShopVideoPerformanceListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


