/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv{}

// Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv struct for Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv
type Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv struct {
    // GMV amount in the corresponding currency.
    Amount *string `json:"amount,omitempty"`
    // GMV currency code (ISO 4217 standard). If LOCAL currency is requested, the value will be the local currency code of where the shop is registered (e.g. GBP).
    Currency *string `json:"currency,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv

// NewAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv instantiates a new Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv() *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv {
    this := Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv{}
    return &this
}

// NewAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmvWithDefaults instantiates a new Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmvWithDefaults() *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv {
    this := Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) SetCurrency(v string) {
    o.Currency = &v
}

func (o Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) UnmarshalJSON(data []byte) (err error) {
    varAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv := _Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv{}

    err = json.Unmarshal(data, &varAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv)

    if err != nil {
        return err
    }

    *o = Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv(varAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv struct {
	value *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv
	isSet bool
}

func (v NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) Get() *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv {
	return v.value
}

func (v *NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) Set(val *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv(val *Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) *NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv {
	return &NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv{value: val, isSet: true}
}

func (v NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsSalesGmv) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


