/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Analytics202509GetShopProductPerformanceListResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Analytics202509GetShopProductPerformanceListResponseData{}

// Analytics202509GetShopProductPerformanceListResponseData struct for Analytics202509GetShopProductPerformanceListResponseData
type Analytics202509GetShopProductPerformanceListResponseData struct {
    // Latest date in local timezone where data is ready (ISO 8601 format).
    LatestAvailableDate *string `json:"latest_available_date,omitempty"`
    // Page token for the next page request.
    NextPageToken *string `json:"next_page_token,omitempty"`
    // List of product performance metrics.
    Products []Analytics202509GetShopProductPerformanceListResponseDataProducts `json:"products,omitempty"`
    // Total number of products.
    TotalCount *int32 `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Analytics202509GetShopProductPerformanceListResponseData Analytics202509GetShopProductPerformanceListResponseData

// NewAnalytics202509GetShopProductPerformanceListResponseData instantiates a new Analytics202509GetShopProductPerformanceListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalytics202509GetShopProductPerformanceListResponseData() *Analytics202509GetShopProductPerformanceListResponseData {
    this := Analytics202509GetShopProductPerformanceListResponseData{}
    return &this
}

// NewAnalytics202509GetShopProductPerformanceListResponseDataWithDefaults instantiates a new Analytics202509GetShopProductPerformanceListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalytics202509GetShopProductPerformanceListResponseDataWithDefaults() *Analytics202509GetShopProductPerformanceListResponseData {
    this := Analytics202509GetShopProductPerformanceListResponseData{}
    return &this
}

// GetLatestAvailableDate returns the LatestAvailableDate field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetLatestAvailableDate() string {
    if o == nil || utils.IsNil(o.LatestAvailableDate) {
        var ret string
        return ret
    }
    return *o.LatestAvailableDate
}

// GetLatestAvailableDateOk returns a tuple with the LatestAvailableDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetLatestAvailableDateOk() (*string, bool) {
    if o == nil || utils.IsNil(o.LatestAvailableDate) {
        return nil, false
    }
    return o.LatestAvailableDate, true
}

// HasLatestAvailableDate returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) HasLatestAvailableDate() bool {
    if o != nil && !utils.IsNil(o.LatestAvailableDate) {
        return true
    }

    return false
}

// SetLatestAvailableDate gets a reference to the given string and assigns it to the LatestAvailableDate field.
func (o *Analytics202509GetShopProductPerformanceListResponseData) SetLatestAvailableDate(v string) {
    o.LatestAvailableDate = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Analytics202509GetShopProductPerformanceListResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetProducts() []Analytics202509GetShopProductPerformanceListResponseDataProducts {
    if o == nil || utils.IsNil(o.Products) {
        var ret []Analytics202509GetShopProductPerformanceListResponseDataProducts
        return ret
    }
    return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetProductsOk() ([]Analytics202509GetShopProductPerformanceListResponseDataProducts, bool) {
    if o == nil || utils.IsNil(o.Products) {
        return nil, false
    }
    return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) HasProducts() bool {
    if o != nil && !utils.IsNil(o.Products) {
        return true
    }

    return false
}

// SetProducts gets a reference to the given []Analytics202509GetShopProductPerformanceListResponseDataProducts and assigns it to the Products field.
func (o *Analytics202509GetShopProductPerformanceListResponseData) SetProducts(v []Analytics202509GetShopProductPerformanceListResponseDataProducts) {
    o.Products = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetTotalCount() int32 {
    if o == nil || utils.IsNil(o.TotalCount) {
        var ret int32
        return ret
    }
    return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) GetTotalCountOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.TotalCount) {
        return nil, false
    }
    return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *Analytics202509GetShopProductPerformanceListResponseData) HasTotalCount() bool {
    if o != nil && !utils.IsNil(o.TotalCount) {
        return true
    }

    return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *Analytics202509GetShopProductPerformanceListResponseData) SetTotalCount(v int32) {
    o.TotalCount = &v
}

func (o Analytics202509GetShopProductPerformanceListResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Analytics202509GetShopProductPerformanceListResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.LatestAvailableDate) {
        toSerialize["latest_available_date"] = o.LatestAvailableDate
    }
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.Products) {
        toSerialize["products"] = o.Products
    }
    if !utils.IsNil(o.TotalCount) {
        toSerialize["total_count"] = o.TotalCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Analytics202509GetShopProductPerformanceListResponseData) UnmarshalJSON(data []byte) (err error) {
    varAnalytics202509GetShopProductPerformanceListResponseData := _Analytics202509GetShopProductPerformanceListResponseData{}

    err = json.Unmarshal(data, &varAnalytics202509GetShopProductPerformanceListResponseData)

    if err != nil {
        return err
    }

    *o = Analytics202509GetShopProductPerformanceListResponseData(varAnalytics202509GetShopProductPerformanceListResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "latest_available_date")
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "products")
        delete(additionalProperties, "total_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAnalytics202509GetShopProductPerformanceListResponseData struct {
	value *Analytics202509GetShopProductPerformanceListResponseData
	isSet bool
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponseData) Get() *Analytics202509GetShopProductPerformanceListResponseData {
	return v.value
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponseData) Set(val *Analytics202509GetShopProductPerformanceListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalytics202509GetShopProductPerformanceListResponseData(val *Analytics202509GetShopProductPerformanceListResponseData) *NullableAnalytics202509GetShopProductPerformanceListResponseData {
	return &NullableAnalytics202509GetShopProductPerformanceListResponseData{value: val, isSet: true}
}

func (v NullableAnalytics202509GetShopProductPerformanceListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalytics202509GetShopProductPerformanceListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


