/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_creator_v202410

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateCreator202410SearchCreatorAffiliateOrdersResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateCreator202410SearchCreatorAffiliateOrdersResponse{}

// AffiliateCreator202410SearchCreatorAffiliateOrdersResponse struct for AffiliateCreator202410SearchCreatorAffiliateOrdersResponse
type AffiliateCreator202410SearchCreatorAffiliateOrdersResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data *AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateCreator202410SearchCreatorAffiliateOrdersResponse AffiliateCreator202410SearchCreatorAffiliateOrdersResponse

// NewAffiliateCreator202410SearchCreatorAffiliateOrdersResponse instantiates a new AffiliateCreator202410SearchCreatorAffiliateOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCreator202410SearchCreatorAffiliateOrdersResponse() *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse {
    this := AffiliateCreator202410SearchCreatorAffiliateOrdersResponse{}
    return &this
}

// NewAffiliateCreator202410SearchCreatorAffiliateOrdersResponseWithDefaults instantiates a new AffiliateCreator202410SearchCreatorAffiliateOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCreator202410SearchCreatorAffiliateOrdersResponseWithDefaults() *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse {
    this := AffiliateCreator202410SearchCreatorAffiliateOrdersResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetData() AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData {
    if o == nil || utils.IsNil(o.Data) {
        var ret AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData
        return ret
    }
    return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetDataOk() (*AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return nil, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData and assigns it to the Data field.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) SetData(v AffiliateCreator202410SearchCreatorAffiliateOrdersResponseData) {
    o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) UnmarshalJSON(data []byte) (err error) {
    varAffiliateCreator202410SearchCreatorAffiliateOrdersResponse := _AffiliateCreator202410SearchCreatorAffiliateOrdersResponse{}

    err = json.Unmarshal(data, &varAffiliateCreator202410SearchCreatorAffiliateOrdersResponse)

    if err != nil {
        return err
    }

    *o = AffiliateCreator202410SearchCreatorAffiliateOrdersResponse(varAffiliateCreator202410SearchCreatorAffiliateOrdersResponse)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "code")
        delete(additionalProperties, "data")
        delete(additionalProperties, "message")
        delete(additionalProperties, "request_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse struct {
	value *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse
	isSet bool
}

func (v NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) Get() *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse {
	return v.value
}

func (v *NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) Set(val *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse(val *AffiliateCreator202410SearchCreatorAffiliateOrdersResponse) *NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse {
	return &NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse{value: val, isSet: true}
}

func (v NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCreator202410SearchCreatorAffiliateOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


