/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_partner_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice{}

// AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice struct for AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice
type AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice struct {
    // The lowest price amount. 
    Amount *string `json:"amount,omitempty"`
    // The currency in the sales region.
    Currency *string `json:"currency,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice

// NewAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice instantiates a new AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice() *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice {
    this := AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice{}
    return &this
}

// NewAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPriceWithDefaults instantiates a new AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPriceWithDefaults() *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice {
    this := AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) SetCurrency(v string) {
    o.Currency = &v
}

func (o AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) UnmarshalJSON(data []byte) (err error) {
    varAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice := _AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice{}

    err = json.Unmarshal(data, &varAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice)

    if err != nil {
        return err
    }

    *o = AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice(varAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice struct {
	value *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice
	isSet bool
}

func (v NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) Get() *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice {
	return v.value
}

func (v *NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) Set(val *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice(val *AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) *NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice {
	return &NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice{value: val, isSet: true}
}

func (v NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


