/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202410

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202410SearchSellerAffiliateOrdersResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202410SearchSellerAffiliateOrdersResponseData{}

// AffiliateSeller202410SearchSellerAffiliateOrdersResponseData struct for AffiliateSeller202410SearchSellerAffiliateOrdersResponseData
type AffiliateSeller202410SearchSellerAffiliateOrdersResponseData struct {
    // An opaque token used to retrieve the next page of a paginated result set. Provide this value in the `page_token` parameter of your request if the current response does not return all the results.
    NextPageToken *string `json:"next_page_token,omitempty"`
    // The returned list of orders.
    Orders []AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders `json:"orders,omitempty"`
    // The total number of orders that matches the query conditions.
    TotalCount *int64 `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202410SearchSellerAffiliateOrdersResponseData AffiliateSeller202410SearchSellerAffiliateOrdersResponseData

// NewAffiliateSeller202410SearchSellerAffiliateOrdersResponseData instantiates a new AffiliateSeller202410SearchSellerAffiliateOrdersResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202410SearchSellerAffiliateOrdersResponseData() *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData {
    this := AffiliateSeller202410SearchSellerAffiliateOrdersResponseData{}
    return &this
}

// NewAffiliateSeller202410SearchSellerAffiliateOrdersResponseDataWithDefaults instantiates a new AffiliateSeller202410SearchSellerAffiliateOrdersResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202410SearchSellerAffiliateOrdersResponseDataWithDefaults() *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData {
    this := AffiliateSeller202410SearchSellerAffiliateOrdersResponseData{}
    return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetOrders() []AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders {
    if o == nil || utils.IsNil(o.Orders) {
        var ret []AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders
        return ret
    }
    return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetOrdersOk() ([]AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders, bool) {
    if o == nil || utils.IsNil(o.Orders) {
        return nil, false
    }
    return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) HasOrders() bool {
    if o != nil && !utils.IsNil(o.Orders) {
        return true
    }

    return false
}

// SetOrders gets a reference to the given []AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders and assigns it to the Orders field.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) SetOrders(v []AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders) {
    o.Orders = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetTotalCount() int64 {
    if o == nil || utils.IsNil(o.TotalCount) {
        var ret int64
        return ret
    }
    return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) GetTotalCountOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TotalCount) {
        return nil, false
    }
    return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) HasTotalCount() bool {
    if o != nil && !utils.IsNil(o.TotalCount) {
        return true
    }

    return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) SetTotalCount(v int64) {
    o.TotalCount = &v
}

func (o AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.Orders) {
        toSerialize["orders"] = o.Orders
    }
    if !utils.IsNil(o.TotalCount) {
        toSerialize["total_count"] = o.TotalCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202410SearchSellerAffiliateOrdersResponseData := _AffiliateSeller202410SearchSellerAffiliateOrdersResponseData{}

    err = json.Unmarshal(data, &varAffiliateSeller202410SearchSellerAffiliateOrdersResponseData)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202410SearchSellerAffiliateOrdersResponseData(varAffiliateSeller202410SearchSellerAffiliateOrdersResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "orders")
        delete(additionalProperties, "total_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData struct {
	value *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData
	isSet bool
}

func (v NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) Get() *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData {
	return v.value
}

func (v *NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) Set(val *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData(val *AffiliateSeller202410SearchSellerAffiliateOrdersResponseData) *NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData {
	return &NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData{value: val, isSet: true}
}

func (v NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202410SearchSellerAffiliateOrdersResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


