/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202508

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange{}

// AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange struct for AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange
type AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange struct {
    // The currency code.
    Currency *string `json:"currency,omitempty"`
    // The formatted range of GPM values associated with the creator. 
    FormattedRange *string `json:"formatted_range,omitempty"`
    // The highest GPM value.
    MaximumAmount *string `json:"maximum_amount,omitempty"`
    // The lowest GPM value.
    MinimumAmount *string `json:"minimum_amount,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange

// NewAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange instantiates a new AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange() *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange {
    this := AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange{}
    return &this
}

// NewAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRangeWithDefaults instantiates a new AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRangeWithDefaults() *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange {
    this := AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange{}
    return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) SetCurrency(v string) {
    o.Currency = &v
}

// GetFormattedRange returns the FormattedRange field value if set, zero value otherwise.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetFormattedRange() string {
    if o == nil || utils.IsNil(o.FormattedRange) {
        var ret string
        return ret
    }
    return *o.FormattedRange
}

// GetFormattedRangeOk returns a tuple with the FormattedRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetFormattedRangeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FormattedRange) {
        return nil, false
    }
    return o.FormattedRange, true
}

// HasFormattedRange returns a boolean if a field has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) HasFormattedRange() bool {
    if o != nil && !utils.IsNil(o.FormattedRange) {
        return true
    }

    return false
}

// SetFormattedRange gets a reference to the given string and assigns it to the FormattedRange field.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) SetFormattedRange(v string) {
    o.FormattedRange = &v
}

// GetMaximumAmount returns the MaximumAmount field value if set, zero value otherwise.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetMaximumAmount() string {
    if o == nil || utils.IsNil(o.MaximumAmount) {
        var ret string
        return ret
    }
    return *o.MaximumAmount
}

// GetMaximumAmountOk returns a tuple with the MaximumAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetMaximumAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.MaximumAmount) {
        return nil, false
    }
    return o.MaximumAmount, true
}

// HasMaximumAmount returns a boolean if a field has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) HasMaximumAmount() bool {
    if o != nil && !utils.IsNil(o.MaximumAmount) {
        return true
    }

    return false
}

// SetMaximumAmount gets a reference to the given string and assigns it to the MaximumAmount field.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) SetMaximumAmount(v string) {
    o.MaximumAmount = &v
}

// GetMinimumAmount returns the MinimumAmount field value if set, zero value otherwise.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetMinimumAmount() string {
    if o == nil || utils.IsNil(o.MinimumAmount) {
        var ret string
        return ret
    }
    return *o.MinimumAmount
}

// GetMinimumAmountOk returns a tuple with the MinimumAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) GetMinimumAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.MinimumAmount) {
        return nil, false
    }
    return o.MinimumAmount, true
}

// HasMinimumAmount returns a boolean if a field has been set.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) HasMinimumAmount() bool {
    if o != nil && !utils.IsNil(o.MinimumAmount) {
        return true
    }

    return false
}

// SetMinimumAmount gets a reference to the given string and assigns it to the MinimumAmount field.
func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) SetMinimumAmount(v string) {
    o.MinimumAmount = &v
}

func (o AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }
    if !utils.IsNil(o.FormattedRange) {
        toSerialize["formatted_range"] = o.FormattedRange
    }
    if !utils.IsNil(o.MaximumAmount) {
        toSerialize["maximum_amount"] = o.MaximumAmount
    }
    if !utils.IsNil(o.MinimumAmount) {
        toSerialize["minimum_amount"] = o.MinimumAmount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange := _AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange{}

    err = json.Unmarshal(data, &varAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange(varAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "currency")
        delete(additionalProperties, "formatted_range")
        delete(additionalProperties, "maximum_amount")
        delete(additionalProperties, "minimum_amount")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange struct {
	value *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange
	isSet bool
}

func (v NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) Get() *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange {
	return v.value
}

func (v *NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) Set(val *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange(val *AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) *NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange {
	return &NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange{value: val, isSet: true}
}

func (v NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


