/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202508

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar{}

// AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar struct for AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar
type AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar struct {
    // The URL for the TikTok creator's avatar image file.
    Url *string `json:"url,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar

// NewAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar instantiates a new AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar() *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar {
    this := AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar{}
    return &this
}

// NewAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatarWithDefaults instantiates a new AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatarWithDefaults() *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar {
    this := AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar{}
    return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) GetUrl() string {
    if o == nil || utils.IsNil(o.Url) {
        var ret string
        return ret
    }
    return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) GetUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Url) {
        return nil, false
    }
    return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) HasUrl() bool {
    if o != nil && !utils.IsNil(o.Url) {
        return true
    }

    return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) SetUrl(v string) {
    o.Url = &v
}

func (o AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Url) {
        toSerialize["url"] = o.Url
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar := _AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar{}

    err = json.Unmarshal(data, &varAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar(varAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "url")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar struct {
	value *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar
	isSet bool
}

func (v NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) Get() *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar {
	return v.value
}

func (v *NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) Set(val *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar(val *AffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) *NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar {
	return &NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar{value: val, isSet: true}
}

func (v NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202508QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


