/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202508

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202508SellerSearchSampleApplicationsResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202508SellerSearchSampleApplicationsResponseData{}

// AffiliateSeller202508SellerSearchSampleApplicationsResponseData struct for AffiliateSeller202508SellerSearchSampleApplicationsResponseData
type AffiliateSeller202508SellerSearchSampleApplicationsResponseData struct {
    // Page token to query next page orders, last page is empty string
    NextPageToken *string `json:"next_page_token,omitempty"`
    // The sample applications from creators
    SampleApplications []AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications `json:"sample_applications,omitempty"`
    // total count
    TotalCount *int64 `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202508SellerSearchSampleApplicationsResponseData AffiliateSeller202508SellerSearchSampleApplicationsResponseData

// NewAffiliateSeller202508SellerSearchSampleApplicationsResponseData instantiates a new AffiliateSeller202508SellerSearchSampleApplicationsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202508SellerSearchSampleApplicationsResponseData() *AffiliateSeller202508SellerSearchSampleApplicationsResponseData {
    this := AffiliateSeller202508SellerSearchSampleApplicationsResponseData{}
    return &this
}

// NewAffiliateSeller202508SellerSearchSampleApplicationsResponseDataWithDefaults instantiates a new AffiliateSeller202508SellerSearchSampleApplicationsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202508SellerSearchSampleApplicationsResponseDataWithDefaults() *AffiliateSeller202508SellerSearchSampleApplicationsResponseData {
    this := AffiliateSeller202508SellerSearchSampleApplicationsResponseData{}
    return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetSampleApplications returns the SampleApplications field value if set, zero value otherwise.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetSampleApplications() []AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications {
    if o == nil || utils.IsNil(o.SampleApplications) {
        var ret []AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications
        return ret
    }
    return o.SampleApplications
}

// GetSampleApplicationsOk returns a tuple with the SampleApplications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetSampleApplicationsOk() ([]AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications, bool) {
    if o == nil || utils.IsNil(o.SampleApplications) {
        return nil, false
    }
    return o.SampleApplications, true
}

// HasSampleApplications returns a boolean if a field has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) HasSampleApplications() bool {
    if o != nil && !utils.IsNil(o.SampleApplications) {
        return true
    }

    return false
}

// SetSampleApplications gets a reference to the given []AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications and assigns it to the SampleApplications field.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) SetSampleApplications(v []AffiliateSeller202508SellerSearchSampleApplicationsResponseDataSampleApplications) {
    o.SampleApplications = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetTotalCount() int64 {
    if o == nil || utils.IsNil(o.TotalCount) {
        var ret int64
        return ret
    }
    return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) GetTotalCountOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TotalCount) {
        return nil, false
    }
    return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) HasTotalCount() bool {
    if o != nil && !utils.IsNil(o.TotalCount) {
        return true
    }

    return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) SetTotalCount(v int64) {
    o.TotalCount = &v
}

func (o AffiliateSeller202508SellerSearchSampleApplicationsResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202508SellerSearchSampleApplicationsResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.SampleApplications) {
        toSerialize["sample_applications"] = o.SampleApplications
    }
    if !utils.IsNil(o.TotalCount) {
        toSerialize["total_count"] = o.TotalCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202508SellerSearchSampleApplicationsResponseData := _AffiliateSeller202508SellerSearchSampleApplicationsResponseData{}

    err = json.Unmarshal(data, &varAffiliateSeller202508SellerSearchSampleApplicationsResponseData)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202508SellerSearchSampleApplicationsResponseData(varAffiliateSeller202508SellerSearchSampleApplicationsResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "sample_applications")
        delete(additionalProperties, "total_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData struct {
	value *AffiliateSeller202508SellerSearchSampleApplicationsResponseData
	isSet bool
}

func (v NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) Get() *AffiliateSeller202508SellerSearchSampleApplicationsResponseData {
	return v.value
}

func (v *NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) Set(val *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData(val *AffiliateSeller202508SellerSearchSampleApplicationsResponseData) *NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData {
	return &NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData{value: val, isSet: true}
}

func (v NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202508SellerSearchSampleApplicationsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


