/*
tiktok shop openapi

Testing AffiliatePartnerV202508APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk_golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "tiktokshop/open/sdk_golang/apis"
)

func Test_sdk_golang_AffiliatePartnerV202508APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AffiliatePartnerV202508APIService AffiliatePartner202508CampaignsCampaignIdProductsProductIdCreatorCreatorTempIdContentStatisticsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var campaignId string
		var productId string
		var creatorTempId string

		resp, httpRes, err := apiClient.AffiliatePartnerV202508API.AffiliatePartner202508CampaignsCampaignIdProductsProductIdCreatorCreatorTempIdContentStatisticsGet(context.Background(), campaignId, productId, creatorTempId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AffiliatePartnerV202508APIService AffiliatePartner202508CampaignsCampaignIdProductsProductIdCreatorCreatorTempIdContentStatisticsSampleStatusGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var campaignId string
		var productId string
		var creatorTempId string

		resp, httpRes, err := apiClient.AffiliatePartnerV202508API.AffiliatePartner202508CampaignsCampaignIdProductsProductIdCreatorCreatorTempIdContentStatisticsSampleStatusGet(context.Background(), campaignId, productId, creatorTempId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
