/*
tiktok shop openapi

Testing AffiliateSellerV202509APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk_golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "tiktokshop/open/sdk_golang/apis"
)

func Test_sdk_golang_AffiliateSellerV202509APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AffiliateSellerV202509APIService AffiliateSeller202509TargetCollaborationTargetCollaborationIdLinkPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var targetCollaborationId string

		resp, httpRes, err := apiClient.AffiliateSellerV202509API.AffiliateSeller202509TargetCollaborationTargetCollaborationIdLinkPost(context.Background(), targetCollaborationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
