/*
tiktok shop openapi

Testing AnalyticsV202512APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk_golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "tiktokshop/open/sdk_golang/apis"
)

func Test_sdk_golang_AnalyticsV202512APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AnalyticsV202512APIService Analytics202512ShopLiveIdProductsPerformanceGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var liveId string

		resp, httpRes, err := apiClient.AnalyticsV202512API.Analytics202512ShopLiveIdProductsPerformanceGet(context.Background(), liveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
