/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Affiliate202309GetCreatorProfileoldResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Affiliate202309GetCreatorProfileoldResponseData{}

// Affiliate202309GetCreatorProfileoldResponseData struct for Affiliate202309GetCreatorProfileoldResponseData
type Affiliate202309GetCreatorProfileoldResponseData struct {
    Avatar *Affiliate202309GetCreatorProfileoldResponseDataAvatar `json:"avatar,omitempty"`
    // The creator's bound partner's ID
    PartnerId *string `json:"partner_id,omitempty"`
    // The creator's bound partner's name
    PartnerName *string `json:"partner_name,omitempty"`
    // The creator's granted permissions
    Permissions []string `json:"permissions,omitempty"`
    // The creator's register region
    RegisterRegion *string `json:"register_region,omitempty"`
    // Represents the regions in which creators can promote products in their showcases, videos, and live streams.
    SelectionRegion *string `json:"selection_region,omitempty"`
    // The creator's seller type if a creator has linked to a TikTok seller
    SellerType *string `json:"seller_type,omitempty"`
    // The creator's username in TikTok App Profile page, like creator_abc123
    UserName *string `json:"user_name,omitempty"`
    // The creator's user type
    UserType *string `json:"user_type,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Affiliate202309GetCreatorProfileoldResponseData Affiliate202309GetCreatorProfileoldResponseData

// NewAffiliate202309GetCreatorProfileoldResponseData instantiates a new Affiliate202309GetCreatorProfileoldResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliate202309GetCreatorProfileoldResponseData() *Affiliate202309GetCreatorProfileoldResponseData {
    this := Affiliate202309GetCreatorProfileoldResponseData{}
    return &this
}

// NewAffiliate202309GetCreatorProfileoldResponseDataWithDefaults instantiates a new Affiliate202309GetCreatorProfileoldResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliate202309GetCreatorProfileoldResponseDataWithDefaults() *Affiliate202309GetCreatorProfileoldResponseData {
    this := Affiliate202309GetCreatorProfileoldResponseData{}
    return &this
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetAvatar() Affiliate202309GetCreatorProfileoldResponseDataAvatar {
    if o == nil || utils.IsNil(o.Avatar) {
        var ret Affiliate202309GetCreatorProfileoldResponseDataAvatar
        return ret
    }
    return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetAvatarOk() (*Affiliate202309GetCreatorProfileoldResponseDataAvatar, bool) {
    if o == nil || utils.IsNil(o.Avatar) {
        return nil, false
    }
    return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasAvatar() bool {
    if o != nil && !utils.IsNil(o.Avatar) {
        return true
    }

    return false
}

// SetAvatar gets a reference to the given Affiliate202309GetCreatorProfileoldResponseDataAvatar and assigns it to the Avatar field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetAvatar(v Affiliate202309GetCreatorProfileoldResponseDataAvatar) {
    o.Avatar = &v
}

// GetPartnerId returns the PartnerId field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPartnerId() string {
    if o == nil || utils.IsNil(o.PartnerId) {
        var ret string
        return ret
    }
    return *o.PartnerId
}

// GetPartnerIdOk returns a tuple with the PartnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPartnerIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PartnerId) {
        return nil, false
    }
    return o.PartnerId, true
}

// HasPartnerId returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasPartnerId() bool {
    if o != nil && !utils.IsNil(o.PartnerId) {
        return true
    }

    return false
}

// SetPartnerId gets a reference to the given string and assigns it to the PartnerId field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetPartnerId(v string) {
    o.PartnerId = &v
}

// GetPartnerName returns the PartnerName field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPartnerName() string {
    if o == nil || utils.IsNil(o.PartnerName) {
        var ret string
        return ret
    }
    return *o.PartnerName
}

// GetPartnerNameOk returns a tuple with the PartnerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPartnerNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PartnerName) {
        return nil, false
    }
    return o.PartnerName, true
}

// HasPartnerName returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasPartnerName() bool {
    if o != nil && !utils.IsNil(o.PartnerName) {
        return true
    }

    return false
}

// SetPartnerName gets a reference to the given string and assigns it to the PartnerName field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetPartnerName(v string) {
    o.PartnerName = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPermissions() []string {
    if o == nil || utils.IsNil(o.Permissions) {
        var ret []string
        return ret
    }
    return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetPermissionsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.Permissions) {
        return nil, false
    }
    return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasPermissions() bool {
    if o != nil && !utils.IsNil(o.Permissions) {
        return true
    }

    return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetPermissions(v []string) {
    o.Permissions = v
}

// GetRegisterRegion returns the RegisterRegion field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetRegisterRegion() string {
    if o == nil || utils.IsNil(o.RegisterRegion) {
        var ret string
        return ret
    }
    return *o.RegisterRegion
}

// GetRegisterRegionOk returns a tuple with the RegisterRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetRegisterRegionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RegisterRegion) {
        return nil, false
    }
    return o.RegisterRegion, true
}

// HasRegisterRegion returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasRegisterRegion() bool {
    if o != nil && !utils.IsNil(o.RegisterRegion) {
        return true
    }

    return false
}

// SetRegisterRegion gets a reference to the given string and assigns it to the RegisterRegion field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetRegisterRegion(v string) {
    o.RegisterRegion = &v
}

// GetSelectionRegion returns the SelectionRegion field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetSelectionRegion() string {
    if o == nil || utils.IsNil(o.SelectionRegion) {
        var ret string
        return ret
    }
    return *o.SelectionRegion
}

// GetSelectionRegionOk returns a tuple with the SelectionRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetSelectionRegionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SelectionRegion) {
        return nil, false
    }
    return o.SelectionRegion, true
}

// HasSelectionRegion returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasSelectionRegion() bool {
    if o != nil && !utils.IsNil(o.SelectionRegion) {
        return true
    }

    return false
}

// SetSelectionRegion gets a reference to the given string and assigns it to the SelectionRegion field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetSelectionRegion(v string) {
    o.SelectionRegion = &v
}

// GetSellerType returns the SellerType field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetSellerType() string {
    if o == nil || utils.IsNil(o.SellerType) {
        var ret string
        return ret
    }
    return *o.SellerType
}

// GetSellerTypeOk returns a tuple with the SellerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetSellerTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerType) {
        return nil, false
    }
    return o.SellerType, true
}

// HasSellerType returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasSellerType() bool {
    if o != nil && !utils.IsNil(o.SellerType) {
        return true
    }

    return false
}

// SetSellerType gets a reference to the given string and assigns it to the SellerType field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetSellerType(v string) {
    o.SellerType = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetUserName() string {
    if o == nil || utils.IsNil(o.UserName) {
        var ret string
        return ret
    }
    return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetUserNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.UserName) {
        return nil, false
    }
    return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasUserName() bool {
    if o != nil && !utils.IsNil(o.UserName) {
        return true
    }

    return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetUserName(v string) {
    o.UserName = &v
}

// GetUserType returns the UserType field value if set, zero value otherwise.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetUserType() string {
    if o == nil || utils.IsNil(o.UserType) {
        var ret string
        return ret
    }
    return *o.UserType
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) GetUserTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.UserType) {
        return nil, false
    }
    return o.UserType, true
}

// HasUserType returns a boolean if a field has been set.
func (o *Affiliate202309GetCreatorProfileoldResponseData) HasUserType() bool {
    if o != nil && !utils.IsNil(o.UserType) {
        return true
    }

    return false
}

// SetUserType gets a reference to the given string and assigns it to the UserType field.
func (o *Affiliate202309GetCreatorProfileoldResponseData) SetUserType(v string) {
    o.UserType = &v
}

func (o Affiliate202309GetCreatorProfileoldResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Affiliate202309GetCreatorProfileoldResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Avatar) {
        toSerialize["avatar"] = o.Avatar
    }
    if !utils.IsNil(o.PartnerId) {
        toSerialize["partner_id"] = o.PartnerId
    }
    if !utils.IsNil(o.PartnerName) {
        toSerialize["partner_name"] = o.PartnerName
    }
    if !utils.IsNil(o.Permissions) {
        toSerialize["permissions"] = o.Permissions
    }
    if !utils.IsNil(o.RegisterRegion) {
        toSerialize["register_region"] = o.RegisterRegion
    }
    if !utils.IsNil(o.SelectionRegion) {
        toSerialize["selection_region"] = o.SelectionRegion
    }
    if !utils.IsNil(o.SellerType) {
        toSerialize["seller_type"] = o.SellerType
    }
    if !utils.IsNil(o.UserName) {
        toSerialize["user_name"] = o.UserName
    }
    if !utils.IsNil(o.UserType) {
        toSerialize["user_type"] = o.UserType
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Affiliate202309GetCreatorProfileoldResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliate202309GetCreatorProfileoldResponseData := _Affiliate202309GetCreatorProfileoldResponseData{}

    err = json.Unmarshal(data, &varAffiliate202309GetCreatorProfileoldResponseData)

    if err != nil {
        return err
    }

    *o = Affiliate202309GetCreatorProfileoldResponseData(varAffiliate202309GetCreatorProfileoldResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "avatar")
        delete(additionalProperties, "partner_id")
        delete(additionalProperties, "partner_name")
        delete(additionalProperties, "permissions")
        delete(additionalProperties, "register_region")
        delete(additionalProperties, "selection_region")
        delete(additionalProperties, "seller_type")
        delete(additionalProperties, "user_name")
        delete(additionalProperties, "user_type")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliate202309GetCreatorProfileoldResponseData struct {
	value *Affiliate202309GetCreatorProfileoldResponseData
	isSet bool
}

func (v NullableAffiliate202309GetCreatorProfileoldResponseData) Get() *Affiliate202309GetCreatorProfileoldResponseData {
	return v.value
}

func (v *NullableAffiliate202309GetCreatorProfileoldResponseData) Set(val *Affiliate202309GetCreatorProfileoldResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliate202309GetCreatorProfileoldResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliate202309GetCreatorProfileoldResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliate202309GetCreatorProfileoldResponseData(val *Affiliate202309GetCreatorProfileoldResponseData) *NullableAffiliate202309GetCreatorProfileoldResponseData {
	return &NullableAffiliate202309GetCreatorProfileoldResponseData{value: val, isSet: true}
}

func (v NullableAffiliate202309GetCreatorProfileoldResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliate202309GetCreatorProfileoldResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


