import apiClient from "./client";
import type {
  MarketplaceSyncHistoryEntry,
  MarketplaceSyncHistoryListResult,
  MarketplaceSyncHistoryFilter,
} from "@/types/shared";

const BASE_PATH = "/marketplace-sync-history";

/**
 * Get marketplace sync history with filters
 * @param filter - Query filters for pagination, platform, operation, status, SKU search, date range
 * @returns List result with entries, total count, and pagination metadata
 */
export async function getMarketplaceSyncHistory(
  filter: MarketplaceSyncHistoryFilter = {},
): Promise<MarketplaceSyncHistoryListResult> {
  // Build query params with URLSearchParams (snake_case keys)
  const params = new URLSearchParams();

  if (filter.page !== undefined) params.append("page", String(filter.page));
  if (filter.page_size !== undefined)
    params.append("page_size", String(filter.page_size));
  if (filter.platform) params.append("platform", filter.platform);
  if (filter.operation) params.append("operation", filter.operation);
  if (filter.status) params.append("status", filter.status);
  if (filter.sku_search) params.append("sku_search", filter.sku_search);
  if (filter.date_from) params.append("date_from", filter.date_from);
  if (filter.date_to) params.append("date_to", filter.date_to);

  const url = params.toString()
    ? `${BASE_PATH}?${params.toString()}`
    : BASE_PATH;

  const response = await apiClient.get<MarketplaceSyncHistoryListResult>(url);

  if (!response.success || !response.data) {
    throw new Error(
      response.error || "Failed to fetch marketplace sync history",
    );
  }

  return response.data;
}

/**
 * Create a new marketplace sync history entry
 * @param entry - Entry data (id, tenant_id, created_at omitted — auto-generated by backend)
 * @returns Created entry with all fields populated
 */
export async function createMarketplaceSyncHistoryEntry(
  entry: Omit<MarketplaceSyncHistoryEntry, "id" | "tenant_id" | "created_at">,
): Promise<MarketplaceSyncHistoryEntry> {
  const response = await apiClient.post<MarketplaceSyncHistoryEntry>(
    BASE_PATH,
    entry,
  );

  if (!response.success || !response.data) {
    throw new Error(
      response.error || "Failed to create marketplace sync history entry",
    );
  }

  return response.data;
}
