/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_creator_v202505

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody{}

// AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody struct for AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody
type AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody struct {
    // If a creator adds products from a campaign, please include the campaign ID. The campaign ID can be found in the Affiliate Center or retrieved using the Get Affiliate Partner Campaign List API.
    CampaignId *string `json:"campaign_id,omitempty"`
    Material *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial `json:"material,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody

// NewAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody instantiates a new AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody() *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody {
    this := AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody{}
    return &this
}

// NewAffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyWithDefaults instantiates a new AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyWithDefaults() *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody {
    this := AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody{}
    return &this
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) GetCampaignId() string {
    if o == nil || utils.IsNil(o.CampaignId) {
        var ret string
        return ret
    }
    return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) GetCampaignIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CampaignId) {
        return nil, false
    }
    return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) HasCampaignId() bool {
    if o != nil && !utils.IsNil(o.CampaignId) {
        return true
    }

    return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) SetCampaignId(v string) {
    o.CampaignId = &v
}

// GetMaterial returns the Material field value if set, zero value otherwise.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) GetMaterial() AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial {
    if o == nil || utils.IsNil(o.Material) {
        var ret AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial
        return ret
    }
    return *o.Material
}

// GetMaterialOk returns a tuple with the Material field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) GetMaterialOk() (*AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial, bool) {
    if o == nil || utils.IsNil(o.Material) {
        return nil, false
    }
    return o.Material, true
}

// HasMaterial returns a boolean if a field has been set.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) HasMaterial() bool {
    if o != nil && !utils.IsNil(o.Material) {
        return true
    }

    return false
}

// SetMaterial gets a reference to the given AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial and assigns it to the Material field.
func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) SetMaterial(v AffiliateCreator202505CreatorGenerateGeneralLinkRequestBodyMaterial) {
    o.Material = &v
}

func (o AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CampaignId) {
        toSerialize["campaign_id"] = o.CampaignId
    }
    if !utils.IsNil(o.Material) {
        toSerialize["material"] = o.Material
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) UnmarshalJSON(data []byte) (err error) {
    varAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody := _AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody{}

    err = json.Unmarshal(data, &varAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody)

    if err != nil {
        return err
    }

    *o = AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody(varAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "campaign_id")
        delete(additionalProperties, "material")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody struct {
	value *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody
	isSet bool
}

func (v NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) Get() *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody {
	return v.value
}

func (v *NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) Set(val *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody(val *AffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) *NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody {
	return &NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody{value: val, isSet: true}
}

func (v NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCreator202505CreatorGenerateGeneralLinkRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


