/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_creator_v202505

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice{}

// AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice struct for AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice
type AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice struct {
    // The value of the price associated with the product. 
    Amount *string `json:"amount,omitempty"`
    // The currency code of the price associated with the product.
    Currency *string `json:"currency,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice

// NewAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice instantiates a new AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice() *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice {
    this := AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice{}
    return &this
}

// NewAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPriceWithDefaults instantiates a new AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPriceWithDefaults() *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice {
    this := AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) SetCurrency(v string) {
    o.Currency = &v
}

func (o AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) UnmarshalJSON(data []byte) (err error) {
    varAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice := _AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice{}

    err = json.Unmarshal(data, &varAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice)

    if err != nil {
        return err
    }

    *o = AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice(varAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice struct {
	value *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice
	isSet bool
}

func (v NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) Get() *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice {
	return v.value
}

func (v *NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) Set(val *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice(val *AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) *NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice {
	return &NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice{value: val, isSet: true}
}

func (v NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


