/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202406

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender{}

// AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender struct for AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender
type AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender struct {
    // Top follower gender category of the creator, \"MALE\" or \"FEMALE\"
    Gender *string `json:"gender,omitempty"`
    // Percentage of top follower gender, scaled up by 10,000 times.  For example, 6524 stands for 0.6524 or 65.24%. You can then infer that the opposite gender would be 0.3476 or 34.76%.
    Percentage *int64 `json:"percentage,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender

// NewAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender instantiates a new AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender() *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender {
    this := AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender{}
    return &this
}

// NewAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGenderWithDefaults instantiates a new AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGenderWithDefaults() *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender {
    this := AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender{}
    return &this
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) GetGender() string {
    if o == nil || utils.IsNil(o.Gender) {
        var ret string
        return ret
    }
    return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) GetGenderOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Gender) {
        return nil, false
    }
    return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) HasGender() bool {
    if o != nil && !utils.IsNil(o.Gender) {
        return true
    }

    return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) SetGender(v string) {
    o.Gender = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) GetPercentage() int64 {
    if o == nil || utils.IsNil(o.Percentage) {
        var ret int64
        return ret
    }
    return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) GetPercentageOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Percentage) {
        return nil, false
    }
    return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) HasPercentage() bool {
    if o != nil && !utils.IsNil(o.Percentage) {
        return true
    }

    return false
}

// SetPercentage gets a reference to the given int64 and assigns it to the Percentage field.
func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) SetPercentage(v int64) {
    o.Percentage = &v
}

func (o AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Gender) {
        toSerialize["gender"] = o.Gender
    }
    if !utils.IsNil(o.Percentage) {
        toSerialize["percentage"] = o.Percentage
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender := _AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender{}

    err = json.Unmarshal(data, &varAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender(varAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "gender")
        delete(additionalProperties, "percentage")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender struct {
	value *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender
	isSet bool
}

func (v NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) Get() *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender {
	return v.value
}

func (v *NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) Set(val *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender(val *AffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) *NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender {
	return &NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender{value: val, isSet: true}
}

func (v NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202406SellerSearchCreatoronMarketplaceResponseDataCreatorsTopFollowerDemographicsMajorGender) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


