/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_creator_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial{}

// AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial struct for AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial
type AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial struct {
    // The original url of the campaign page, which will be returned after verified and concatenated with chainkey and other event tracking parameters.
    CampaignUrl *string `json:"campaign_url,omitempty"`
    // The ID of product/campiagn/showcase that our partner wants to promote. We use this material id to generate the sharing link
    Id *string `json:"id,omitempty"`
    // You can use the following enumerations: - PRODUCT - CAMPAIGN - SHOWCASE When `type==PRODUCT`, use pid as `id`; when `type==CAMPAIGN`, use campaign ID as `id`, and pass in `campaign_url`; when `type==SHOWCASE`, no need to pass in `id` and `campaign_url`.
    Type *string `json:"type,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial

// NewAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial instantiates a new AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial() *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial {
    this := AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial{}
    return &this
}

// NewAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterialWithDefaults instantiates a new AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterialWithDefaults() *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial {
    this := AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial{}
    return &this
}

// GetCampaignUrl returns the CampaignUrl field value if set, zero value otherwise.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetCampaignUrl() string {
    if o == nil || utils.IsNil(o.CampaignUrl) {
        var ret string
        return ret
    }
    return *o.CampaignUrl
}

// GetCampaignUrlOk returns a tuple with the CampaignUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetCampaignUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CampaignUrl) {
        return nil, false
    }
    return o.CampaignUrl, true
}

// HasCampaignUrl returns a boolean if a field has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) HasCampaignUrl() bool {
    if o != nil && !utils.IsNil(o.CampaignUrl) {
        return true
    }

    return false
}

// SetCampaignUrl gets a reference to the given string and assigns it to the CampaignUrl field.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) SetCampaignUrl(v string) {
    o.CampaignUrl = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) SetId(v string) {
    o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetType() string {
    if o == nil || utils.IsNil(o.Type) {
        var ret string
        return ret
    }
    return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) GetTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Type) {
        return nil, false
    }
    return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) HasType() bool {
    if o != nil && !utils.IsNil(o.Type) {
        return true
    }

    return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) SetType(v string) {
    o.Type = &v
}

func (o AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CampaignUrl) {
        toSerialize["campaign_url"] = o.CampaignUrl
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Type) {
        toSerialize["type"] = o.Type
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) UnmarshalJSON(data []byte) (err error) {
    varAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial := _AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial{}

    err = json.Unmarshal(data, &varAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial)

    if err != nil {
        return err
    }

    *o = AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial(varAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "campaign_url")
        delete(additionalProperties, "id")
        delete(additionalProperties, "type")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial struct {
	value *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial
	isSet bool
}

func (v NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) Get() *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial {
	return v.value
}

func (v *NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) Set(val *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial(val *AffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) *NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial {
	return &NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial{value: val, isSet: true}
}

func (v NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateCreator202501GenerateAffiliateSharingLinkRequestBodyMaterial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


