/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apis

import (
    "bytes"
    "context"
    "io"
    "net/http"
    "net/url"

    "tiktokshop/open/sdk_golang/models/affiliate_creator/v202508"
)


// AffiliateCreatorV202508APIService AffiliateCreatorV202508API service
type AffiliateCreatorV202508APIService service

type ApiAffiliateCreator202508ProfilesGetRequest struct {
    ctx context.Context
    ApiService *AffiliateCreatorV202508APIService
    xTtsAccessToken *string
    contentType *string
}

// 
func (r ApiAffiliateCreator202508ProfilesGetRequest) XTtsAccessToken(xTtsAccessToken string) ApiAffiliateCreator202508ProfilesGetRequest {
    r.xTtsAccessToken = &xTtsAccessToken
    return r
}
// Allowed type: application/json
func (r ApiAffiliateCreator202508ProfilesGetRequest) ContentType(contentType string) ApiAffiliateCreator202508ProfilesGetRequest {
    r.contentType = &contentType
    return r
}
func (r ApiAffiliateCreator202508ProfilesGetRequest) Execute() (*affiliate_creator_v202508.AffiliateCreator202508GetCreatorProfileResponse, *http.Response, error) {
    return r.ApiService.AffiliateCreator202508ProfilesGetExecute(r)
}

/*
AffiliateCreator202508ProfilesGet GetCreatorProfile
This API gets the creator profile information.

@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
@return ApiAffiliateCreator202508ProfilesGetRequest
*/
func (a *AffiliateCreatorV202508APIService) AffiliateCreator202508ProfilesGet(ctx context.Context) ApiAffiliateCreator202508ProfilesGetRequest {
    return ApiAffiliateCreator202508ProfilesGetRequest{
        ApiService: a,
        ctx: ctx,
    }
}

// Execute executes the request
//  @return AffiliateCreator202508GetCreatorProfileResponse
func (a *AffiliateCreatorV202508APIService) AffiliateCreator202508ProfilesGetExecute(r ApiAffiliateCreator202508ProfilesGetRequest) (*affiliate_creator_v202508.AffiliateCreator202508GetCreatorProfileResponse, *http.Response, error) {
    var (
        localVarHTTPMethod   = http.MethodGet
        localVarPostBody     interface{}
        formFiles            []formFile
        localVarReturnValue  *affiliate_creator_v202508.AffiliateCreator202508GetCreatorProfileResponse
    )

    localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AffiliateCreatorV202508APIService.AffiliateCreator202508ProfilesGet")
    if err != nil {
        return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
    }

    localVarPath := localBasePath + "/affiliate_creator/202508/profiles"

    localVarHeaderParams := make(map[string]string)
    localVarQueryParams := url.Values{}
    localVarFormParams := url.Values{}
    if r.xTtsAccessToken == nil {
        return localVarReturnValue, nil, reportError("xTtsAccessToken is required and must be specified")
    }
    if r.contentType == nil {
        return localVarReturnValue, nil, reportError("contentType is required and must be specified")
    }

    // to determine the Content-Type header
    localVarHTTPContentTypes := []string{}

    // set Content-Type header
    localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
    if localVarHTTPContentType != "" {
        localVarHeaderParams["Content-Type"] = localVarHTTPContentType
    }

    // to determine the Accept header
    localVarHTTPHeaderAccepts := []string{"application/json"}

    // set Accept header
    localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
    if localVarHTTPHeaderAccept != "" {
        localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
    }
    parameterAddToHeaderOrQuery(localVarHeaderParams, "x-tts-access-token", r.xTtsAccessToken, "")
    parameterAddToHeaderOrQuery(localVarHeaderParams, "Content-Type", r.contentType, "")
    req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
    if err != nil {
        return localVarReturnValue, nil, err
    }

    localVarHTTPResponse, err := a.client.callAPI(req)
    if err != nil || localVarHTTPResponse == nil {
        return localVarReturnValue, localVarHTTPResponse, err
    }

    localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
    localVarHTTPResponse.Body.Close()
    localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
    if err != nil {
        return localVarReturnValue, localVarHTTPResponse, err
    }

    if localVarHTTPResponse.StatusCode >= 300 {
        newErr := &GenericOpenAPIError{
            body:  localVarBody,
            error: localVarHTTPResponse.Status,
        }
        return localVarReturnValue, localVarHTTPResponse, newErr
    }

    err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
    if err != nil {
        newErr := &GenericOpenAPIError{
            body:  localVarBody,
            error: err.Error(),
        }
        return localVarReturnValue, localVarHTTPResponse, newErr
    }

    return localVarReturnValue, localVarHTTPResponse, nil
}
