/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202505

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}

// AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct for AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar
type AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct {
    // The URL for the creator's TikTok profile avatar.
    Url *string `json:"url,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar

// NewAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar instantiates a new AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar() *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
    this := AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}
    return &this
}

// NewAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatarWithDefaults instantiates a new AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatarWithDefaults() *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
    this := AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}
    return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) GetUrl() string {
    if o == nil || utils.IsNil(o.Url) {
        var ret string
        return ret
    }
    return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) GetUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Url) {
        return nil, false
    }
    return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) HasUrl() bool {
    if o != nil && !utils.IsNil(o.Url) {
        return true
    }

    return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) SetUrl(v string) {
    o.Url = &v
}

func (o AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Url) {
        toSerialize["url"] = o.Url
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar := _AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{}

    err = json.Unmarshal(data, &varAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar(varAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "url")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar struct {
	value *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar
	isSet bool
}

func (v NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Get() *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
	return v.value
}

func (v *NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Set(val *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar(val *AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) *NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar {
	return &NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar{value: val, isSet: true}
}

func (v NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


