/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_partner_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData{}

// AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData struct for AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData
type AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData struct {
    // Querying next page need this token.
    NextPageToken *string `json:"next_page_token,omitempty"`
    // A list of objects representing information about the Affiliate Creator associated with the product promotion.
    PromotionCreators []AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators `json:"promotion_creators,omitempty"`
    // The total number of creators involved in the campaign.
    TotalCreatorCount *int64 `json:"total_creator_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData

// NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData instantiates a new AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData {
    this := AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData{}
    return &this
}

// NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataWithDefaults instantiates a new AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataWithDefaults() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData {
    this := AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData{}
    return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetPromotionCreators returns the PromotionCreators field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetPromotionCreators() []AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators {
    if o == nil || utils.IsNil(o.PromotionCreators) {
        var ret []AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators
        return ret
    }
    return o.PromotionCreators
}

// GetPromotionCreatorsOk returns a tuple with the PromotionCreators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetPromotionCreatorsOk() ([]AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators, bool) {
    if o == nil || utils.IsNil(o.PromotionCreators) {
        return nil, false
    }
    return o.PromotionCreators, true
}

// HasPromotionCreators returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) HasPromotionCreators() bool {
    if o != nil && !utils.IsNil(o.PromotionCreators) {
        return true
    }

    return false
}

// SetPromotionCreators gets a reference to the given []AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators and assigns it to the PromotionCreators field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) SetPromotionCreators(v []AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators) {
    o.PromotionCreators = v
}

// GetTotalCreatorCount returns the TotalCreatorCount field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetTotalCreatorCount() int64 {
    if o == nil || utils.IsNil(o.TotalCreatorCount) {
        var ret int64
        return ret
    }
    return *o.TotalCreatorCount
}

// GetTotalCreatorCountOk returns a tuple with the TotalCreatorCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) GetTotalCreatorCountOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TotalCreatorCount) {
        return nil, false
    }
    return o.TotalCreatorCount, true
}

// HasTotalCreatorCount returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) HasTotalCreatorCount() bool {
    if o != nil && !utils.IsNil(o.TotalCreatorCount) {
        return true
    }

    return false
}

// SetTotalCreatorCount gets a reference to the given int64 and assigns it to the TotalCreatorCount field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) SetTotalCreatorCount(v int64) {
    o.TotalCreatorCount = &v
}

func (o AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.PromotionCreators) {
        toSerialize["promotion_creators"] = o.PromotionCreators
    }
    if !utils.IsNil(o.TotalCreatorCount) {
        toSerialize["total_creator_count"] = o.TotalCreatorCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData := _AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData{}

    err = json.Unmarshal(data, &varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData)

    if err != nil {
        return err
    }

    *o = AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData(varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "promotion_creators")
        delete(additionalProperties, "total_creator_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData struct {
	value *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData
	isSet bool
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) Get() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData {
	return v.value
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) Set(val *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData(val *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData {
	return &NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData{value: val, isSet: true}
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


