/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_partner_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator{}

// AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator struct for AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator
type AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator struct {
    // A URL for the creator's avatar image in the TikTok CDN.
    AvatarUrl *string `json:"avatar_url,omitempty"`
    // A time-limited identifier associated with the creator that is valid for one hour. This identifier is valid to retrieve content performance data associated with the creator.
    CreatorTempId *string `json:"creator_temp_id,omitempty"`
    // The total count of TikTok followers for the creator.
    FollowerNum *int64 `json:"follower_num,omitempty"`
    // The TikTok nickname of the creator.
    NickName *string `json:"nick_name,omitempty"`
    // user name
    UserName *string `json:"user_name,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator

// NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator instantiates a new AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator {
    this := AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator{}
    return &this
}

// NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreatorWithDefaults instantiates a new AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreatorWithDefaults() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator {
    this := AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator{}
    return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetAvatarUrl() string {
    if o == nil || utils.IsNil(o.AvatarUrl) {
        var ret string
        return ret
    }
    return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetAvatarUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.AvatarUrl) {
        return nil, false
    }
    return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) HasAvatarUrl() bool {
    if o != nil && !utils.IsNil(o.AvatarUrl) {
        return true
    }

    return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) SetAvatarUrl(v string) {
    o.AvatarUrl = &v
}

// GetCreatorTempId returns the CreatorTempId field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetCreatorTempId() string {
    if o == nil || utils.IsNil(o.CreatorTempId) {
        var ret string
        return ret
    }
    return *o.CreatorTempId
}

// GetCreatorTempIdOk returns a tuple with the CreatorTempId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetCreatorTempIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CreatorTempId) {
        return nil, false
    }
    return o.CreatorTempId, true
}

// HasCreatorTempId returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) HasCreatorTempId() bool {
    if o != nil && !utils.IsNil(o.CreatorTempId) {
        return true
    }

    return false
}

// SetCreatorTempId gets a reference to the given string and assigns it to the CreatorTempId field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) SetCreatorTempId(v string) {
    o.CreatorTempId = &v
}

// GetFollowerNum returns the FollowerNum field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetFollowerNum() int64 {
    if o == nil || utils.IsNil(o.FollowerNum) {
        var ret int64
        return ret
    }
    return *o.FollowerNum
}

// GetFollowerNumOk returns a tuple with the FollowerNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetFollowerNumOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.FollowerNum) {
        return nil, false
    }
    return o.FollowerNum, true
}

// HasFollowerNum returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) HasFollowerNum() bool {
    if o != nil && !utils.IsNil(o.FollowerNum) {
        return true
    }

    return false
}

// SetFollowerNum gets a reference to the given int64 and assigns it to the FollowerNum field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) SetFollowerNum(v int64) {
    o.FollowerNum = &v
}

// GetNickName returns the NickName field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetNickName() string {
    if o == nil || utils.IsNil(o.NickName) {
        var ret string
        return ret
    }
    return *o.NickName
}

// GetNickNameOk returns a tuple with the NickName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetNickNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NickName) {
        return nil, false
    }
    return o.NickName, true
}

// HasNickName returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) HasNickName() bool {
    if o != nil && !utils.IsNil(o.NickName) {
        return true
    }

    return false
}

// SetNickName gets a reference to the given string and assigns it to the NickName field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) SetNickName(v string) {
    o.NickName = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetUserName() string {
    if o == nil || utils.IsNil(o.UserName) {
        var ret string
        return ret
    }
    return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) GetUserNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.UserName) {
        return nil, false
    }
    return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) HasUserName() bool {
    if o != nil && !utils.IsNil(o.UserName) {
        return true
    }

    return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) SetUserName(v string) {
    o.UserName = &v
}

func (o AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.AvatarUrl) {
        toSerialize["avatar_url"] = o.AvatarUrl
    }
    if !utils.IsNil(o.CreatorTempId) {
        toSerialize["creator_temp_id"] = o.CreatorTempId
    }
    if !utils.IsNil(o.FollowerNum) {
        toSerialize["follower_num"] = o.FollowerNum
    }
    if !utils.IsNil(o.NickName) {
        toSerialize["nick_name"] = o.NickName
    }
    if !utils.IsNil(o.UserName) {
        toSerialize["user_name"] = o.UserName
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) UnmarshalJSON(data []byte) (err error) {
    varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator := _AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator{}

    err = json.Unmarshal(data, &varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator)

    if err != nil {
        return err
    }

    *o = AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator(varAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "avatar_url")
        delete(additionalProperties, "creator_temp_id")
        delete(additionalProperties, "follower_num")
        delete(additionalProperties, "nick_name")
        delete(additionalProperties, "user_name")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator struct {
	value *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator
	isSet bool
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) Get() *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator {
	return v.value
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) Set(val *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator(val *AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator {
	return &NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator{value: val, isSet: true}
}

func (v NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


