/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_partner_v202411

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus{}

// AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus struct for AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus
type AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus struct {
    ActualCommissionBase *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase `json:"actual_commission_base,omitempty"`
    ActualCreatorCommission *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission `json:"actual_creator_commission,omitempty"`
    ActualCreatorCommissionRewardFee *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee `json:"actual_creator_commission_reward_fee,omitempty"`
    ActualPartnerCommissionRewardFee *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee `json:"actual_partner_commission_reward_fee,omitempty"`
    ActualTapCommission *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission `json:"actual_tap_commission,omitempty"`
    // New seller campaign 
    CampaignId *string `json:"campaign_id,omitempty"`
    // Unique identifier for content
    ContentId *string `json:"content_id,omitempty"`
    // The content format of the creator content through which the order was created. Possible values: - SHOP - VIDEO - LIVE - PRE_LIVE - PROMOTION_PAGE - LINKSHARE
    ContentType *string `json:"content_type,omitempty"`
    // Between TAP & creator percentage commission
    CreatorCommissionRate *int64 `json:"creator_commission_rate,omitempty"`
    // The commission reward rate affiliate partners allocate to creators
    CreatorCommissionRewardRate *int64 `json:"creator_commission_reward_rate,omitempty"`
    // Creator username
    CreatorUsername *string `json:"creator_username,omitempty"`
    EstimatedCommissionBase *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase `json:"estimated_commission_base,omitempty"`
    EstimatedCreatorCommission *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission `json:"estimated_creator_commission,omitempty"`
    EstimatedCreatorCommissionRewardFee *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee `json:"estimated_creator_commission_reward_fee,omitempty"`
    EstimatedPartnerCommissionRewardFee *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee `json:"estimated_partner_commission_reward_fee,omitempty"`
    EstimatedTapCommission *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission `json:"estimated_tap_commission,omitempty"`
    // sku ID
    Id *string `json:"id,omitempty"`
    // The additional commission rate TikTok Shop offers to affiliate partners for driving product sales in specific campaigns
    PartnerCommissionRewardRate *int64 `json:"partner_commission_reward_rate,omitempty"`
    Price *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice `json:"price,omitempty"`
    // Unique identifier for Product
    ProductId *string `json:"product_id,omitempty"`
    // Product name / description
    ProductName *string `json:"product_name,omitempty"`
    // Total sku quantity per order
    Quantity *int32 `json:"quantity,omitempty"`
    // Number of sku refunded per order
    RefundedQuantity *int32 `json:"refunded_quantity,omitempty"`
    // Number of sku returned per order
    ReturnedQuantity *int32 `json:"returned_quantity,omitempty"`
    // Between seller & TAP percentage commission
    TapCommissionRate *int64 `json:"tap_commission_rate,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus

// NewAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus instantiates a new AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus() *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus {
    this := AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus{}
    return &this
}

// NewAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusWithDefaults instantiates a new AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusWithDefaults() *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus {
    this := AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus{}
    return &this
}

// GetActualCommissionBase returns the ActualCommissionBase field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCommissionBase() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase {
    if o == nil || utils.IsNil(o.ActualCommissionBase) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase
        return ret
    }
    return *o.ActualCommissionBase
}

// GetActualCommissionBaseOk returns a tuple with the ActualCommissionBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCommissionBaseOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase, bool) {
    if o == nil || utils.IsNil(o.ActualCommissionBase) {
        return nil, false
    }
    return o.ActualCommissionBase, true
}

// HasActualCommissionBase returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasActualCommissionBase() bool {
    if o != nil && !utils.IsNil(o.ActualCommissionBase) {
        return true
    }

    return false
}

// SetActualCommissionBase gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase and assigns it to the ActualCommissionBase field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetActualCommissionBase(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase) {
    o.ActualCommissionBase = &v
}

// GetActualCreatorCommission returns the ActualCreatorCommission field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCreatorCommission() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission {
    if o == nil || utils.IsNil(o.ActualCreatorCommission) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission
        return ret
    }
    return *o.ActualCreatorCommission
}

// GetActualCreatorCommissionOk returns a tuple with the ActualCreatorCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCreatorCommissionOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission, bool) {
    if o == nil || utils.IsNil(o.ActualCreatorCommission) {
        return nil, false
    }
    return o.ActualCreatorCommission, true
}

// HasActualCreatorCommission returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasActualCreatorCommission() bool {
    if o != nil && !utils.IsNil(o.ActualCreatorCommission) {
        return true
    }

    return false
}

// SetActualCreatorCommission gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission and assigns it to the ActualCreatorCommission field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetActualCreatorCommission(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission) {
    o.ActualCreatorCommission = &v
}

// GetActualCreatorCommissionRewardFee returns the ActualCreatorCommissionRewardFee field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCreatorCommissionRewardFee() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee {
    if o == nil || utils.IsNil(o.ActualCreatorCommissionRewardFee) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee
        return ret
    }
    return *o.ActualCreatorCommissionRewardFee
}

// GetActualCreatorCommissionRewardFeeOk returns a tuple with the ActualCreatorCommissionRewardFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualCreatorCommissionRewardFeeOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee, bool) {
    if o == nil || utils.IsNil(o.ActualCreatorCommissionRewardFee) {
        return nil, false
    }
    return o.ActualCreatorCommissionRewardFee, true
}

// HasActualCreatorCommissionRewardFee returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasActualCreatorCommissionRewardFee() bool {
    if o != nil && !utils.IsNil(o.ActualCreatorCommissionRewardFee) {
        return true
    }

    return false
}

// SetActualCreatorCommissionRewardFee gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee and assigns it to the ActualCreatorCommissionRewardFee field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetActualCreatorCommissionRewardFee(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee) {
    o.ActualCreatorCommissionRewardFee = &v
}

// GetActualPartnerCommissionRewardFee returns the ActualPartnerCommissionRewardFee field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualPartnerCommissionRewardFee() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee {
    if o == nil || utils.IsNil(o.ActualPartnerCommissionRewardFee) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee
        return ret
    }
    return *o.ActualPartnerCommissionRewardFee
}

// GetActualPartnerCommissionRewardFeeOk returns a tuple with the ActualPartnerCommissionRewardFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualPartnerCommissionRewardFeeOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee, bool) {
    if o == nil || utils.IsNil(o.ActualPartnerCommissionRewardFee) {
        return nil, false
    }
    return o.ActualPartnerCommissionRewardFee, true
}

// HasActualPartnerCommissionRewardFee returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasActualPartnerCommissionRewardFee() bool {
    if o != nil && !utils.IsNil(o.ActualPartnerCommissionRewardFee) {
        return true
    }

    return false
}

// SetActualPartnerCommissionRewardFee gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee and assigns it to the ActualPartnerCommissionRewardFee field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetActualPartnerCommissionRewardFee(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee) {
    o.ActualPartnerCommissionRewardFee = &v
}

// GetActualTapCommission returns the ActualTapCommission field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualTapCommission() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission {
    if o == nil || utils.IsNil(o.ActualTapCommission) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission
        return ret
    }
    return *o.ActualTapCommission
}

// GetActualTapCommissionOk returns a tuple with the ActualTapCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetActualTapCommissionOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission, bool) {
    if o == nil || utils.IsNil(o.ActualTapCommission) {
        return nil, false
    }
    return o.ActualTapCommission, true
}

// HasActualTapCommission returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasActualTapCommission() bool {
    if o != nil && !utils.IsNil(o.ActualTapCommission) {
        return true
    }

    return false
}

// SetActualTapCommission gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission and assigns it to the ActualTapCommission field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetActualTapCommission(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission) {
    o.ActualTapCommission = &v
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCampaignId() string {
    if o == nil || utils.IsNil(o.CampaignId) {
        var ret string
        return ret
    }
    return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCampaignIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CampaignId) {
        return nil, false
    }
    return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasCampaignId() bool {
    if o != nil && !utils.IsNil(o.CampaignId) {
        return true
    }

    return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetCampaignId(v string) {
    o.CampaignId = &v
}

// GetContentId returns the ContentId field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetContentId() string {
    if o == nil || utils.IsNil(o.ContentId) {
        var ret string
        return ret
    }
    return *o.ContentId
}

// GetContentIdOk returns a tuple with the ContentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetContentIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ContentId) {
        return nil, false
    }
    return o.ContentId, true
}

// HasContentId returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasContentId() bool {
    if o != nil && !utils.IsNil(o.ContentId) {
        return true
    }

    return false
}

// SetContentId gets a reference to the given string and assigns it to the ContentId field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetContentId(v string) {
    o.ContentId = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetContentType() string {
    if o == nil || utils.IsNil(o.ContentType) {
        var ret string
        return ret
    }
    return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetContentTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ContentType) {
        return nil, false
    }
    return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasContentType() bool {
    if o != nil && !utils.IsNil(o.ContentType) {
        return true
    }

    return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetContentType(v string) {
    o.ContentType = &v
}

// GetCreatorCommissionRate returns the CreatorCommissionRate field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorCommissionRate() int64 {
    if o == nil || utils.IsNil(o.CreatorCommissionRate) {
        var ret int64
        return ret
    }
    return *o.CreatorCommissionRate
}

// GetCreatorCommissionRateOk returns a tuple with the CreatorCommissionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorCommissionRateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.CreatorCommissionRate) {
        return nil, false
    }
    return o.CreatorCommissionRate, true
}

// HasCreatorCommissionRate returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasCreatorCommissionRate() bool {
    if o != nil && !utils.IsNil(o.CreatorCommissionRate) {
        return true
    }

    return false
}

// SetCreatorCommissionRate gets a reference to the given int64 and assigns it to the CreatorCommissionRate field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetCreatorCommissionRate(v int64) {
    o.CreatorCommissionRate = &v
}

// GetCreatorCommissionRewardRate returns the CreatorCommissionRewardRate field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorCommissionRewardRate() int64 {
    if o == nil || utils.IsNil(o.CreatorCommissionRewardRate) {
        var ret int64
        return ret
    }
    return *o.CreatorCommissionRewardRate
}

// GetCreatorCommissionRewardRateOk returns a tuple with the CreatorCommissionRewardRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorCommissionRewardRateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.CreatorCommissionRewardRate) {
        return nil, false
    }
    return o.CreatorCommissionRewardRate, true
}

// HasCreatorCommissionRewardRate returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasCreatorCommissionRewardRate() bool {
    if o != nil && !utils.IsNil(o.CreatorCommissionRewardRate) {
        return true
    }

    return false
}

// SetCreatorCommissionRewardRate gets a reference to the given int64 and assigns it to the CreatorCommissionRewardRate field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetCreatorCommissionRewardRate(v int64) {
    o.CreatorCommissionRewardRate = &v
}

// GetCreatorUsername returns the CreatorUsername field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorUsername() string {
    if o == nil || utils.IsNil(o.CreatorUsername) {
        var ret string
        return ret
    }
    return *o.CreatorUsername
}

// GetCreatorUsernameOk returns a tuple with the CreatorUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetCreatorUsernameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CreatorUsername) {
        return nil, false
    }
    return o.CreatorUsername, true
}

// HasCreatorUsername returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasCreatorUsername() bool {
    if o != nil && !utils.IsNil(o.CreatorUsername) {
        return true
    }

    return false
}

// SetCreatorUsername gets a reference to the given string and assigns it to the CreatorUsername field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetCreatorUsername(v string) {
    o.CreatorUsername = &v
}

// GetEstimatedCommissionBase returns the EstimatedCommissionBase field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCommissionBase() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase {
    if o == nil || utils.IsNil(o.EstimatedCommissionBase) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase
        return ret
    }
    return *o.EstimatedCommissionBase
}

// GetEstimatedCommissionBaseOk returns a tuple with the EstimatedCommissionBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCommissionBaseOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase, bool) {
    if o == nil || utils.IsNil(o.EstimatedCommissionBase) {
        return nil, false
    }
    return o.EstimatedCommissionBase, true
}

// HasEstimatedCommissionBase returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasEstimatedCommissionBase() bool {
    if o != nil && !utils.IsNil(o.EstimatedCommissionBase) {
        return true
    }

    return false
}

// SetEstimatedCommissionBase gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase and assigns it to the EstimatedCommissionBase field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetEstimatedCommissionBase(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase) {
    o.EstimatedCommissionBase = &v
}

// GetEstimatedCreatorCommission returns the EstimatedCreatorCommission field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCreatorCommission() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission {
    if o == nil || utils.IsNil(o.EstimatedCreatorCommission) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission
        return ret
    }
    return *o.EstimatedCreatorCommission
}

// GetEstimatedCreatorCommissionOk returns a tuple with the EstimatedCreatorCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCreatorCommissionOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission, bool) {
    if o == nil || utils.IsNil(o.EstimatedCreatorCommission) {
        return nil, false
    }
    return o.EstimatedCreatorCommission, true
}

// HasEstimatedCreatorCommission returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasEstimatedCreatorCommission() bool {
    if o != nil && !utils.IsNil(o.EstimatedCreatorCommission) {
        return true
    }

    return false
}

// SetEstimatedCreatorCommission gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission and assigns it to the EstimatedCreatorCommission field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetEstimatedCreatorCommission(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission) {
    o.EstimatedCreatorCommission = &v
}

// GetEstimatedCreatorCommissionRewardFee returns the EstimatedCreatorCommissionRewardFee field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCreatorCommissionRewardFee() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee {
    if o == nil || utils.IsNil(o.EstimatedCreatorCommissionRewardFee) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee
        return ret
    }
    return *o.EstimatedCreatorCommissionRewardFee
}

// GetEstimatedCreatorCommissionRewardFeeOk returns a tuple with the EstimatedCreatorCommissionRewardFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedCreatorCommissionRewardFeeOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee, bool) {
    if o == nil || utils.IsNil(o.EstimatedCreatorCommissionRewardFee) {
        return nil, false
    }
    return o.EstimatedCreatorCommissionRewardFee, true
}

// HasEstimatedCreatorCommissionRewardFee returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasEstimatedCreatorCommissionRewardFee() bool {
    if o != nil && !utils.IsNil(o.EstimatedCreatorCommissionRewardFee) {
        return true
    }

    return false
}

// SetEstimatedCreatorCommissionRewardFee gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee and assigns it to the EstimatedCreatorCommissionRewardFee field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetEstimatedCreatorCommissionRewardFee(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee) {
    o.EstimatedCreatorCommissionRewardFee = &v
}

// GetEstimatedPartnerCommissionRewardFee returns the EstimatedPartnerCommissionRewardFee field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedPartnerCommissionRewardFee() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee {
    if o == nil || utils.IsNil(o.EstimatedPartnerCommissionRewardFee) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee
        return ret
    }
    return *o.EstimatedPartnerCommissionRewardFee
}

// GetEstimatedPartnerCommissionRewardFeeOk returns a tuple with the EstimatedPartnerCommissionRewardFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedPartnerCommissionRewardFeeOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee, bool) {
    if o == nil || utils.IsNil(o.EstimatedPartnerCommissionRewardFee) {
        return nil, false
    }
    return o.EstimatedPartnerCommissionRewardFee, true
}

// HasEstimatedPartnerCommissionRewardFee returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasEstimatedPartnerCommissionRewardFee() bool {
    if o != nil && !utils.IsNil(o.EstimatedPartnerCommissionRewardFee) {
        return true
    }

    return false
}

// SetEstimatedPartnerCommissionRewardFee gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee and assigns it to the EstimatedPartnerCommissionRewardFee field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetEstimatedPartnerCommissionRewardFee(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee) {
    o.EstimatedPartnerCommissionRewardFee = &v
}

// GetEstimatedTapCommission returns the EstimatedTapCommission field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedTapCommission() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission {
    if o == nil || utils.IsNil(o.EstimatedTapCommission) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission
        return ret
    }
    return *o.EstimatedTapCommission
}

// GetEstimatedTapCommissionOk returns a tuple with the EstimatedTapCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetEstimatedTapCommissionOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission, bool) {
    if o == nil || utils.IsNil(o.EstimatedTapCommission) {
        return nil, false
    }
    return o.EstimatedTapCommission, true
}

// HasEstimatedTapCommission returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasEstimatedTapCommission() bool {
    if o != nil && !utils.IsNil(o.EstimatedTapCommission) {
        return true
    }

    return false
}

// SetEstimatedTapCommission gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission and assigns it to the EstimatedTapCommission field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetEstimatedTapCommission(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission) {
    o.EstimatedTapCommission = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetId(v string) {
    o.Id = &v
}

// GetPartnerCommissionRewardRate returns the PartnerCommissionRewardRate field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetPartnerCommissionRewardRate() int64 {
    if o == nil || utils.IsNil(o.PartnerCommissionRewardRate) {
        var ret int64
        return ret
    }
    return *o.PartnerCommissionRewardRate
}

// GetPartnerCommissionRewardRateOk returns a tuple with the PartnerCommissionRewardRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetPartnerCommissionRewardRateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.PartnerCommissionRewardRate) {
        return nil, false
    }
    return o.PartnerCommissionRewardRate, true
}

// HasPartnerCommissionRewardRate returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasPartnerCommissionRewardRate() bool {
    if o != nil && !utils.IsNil(o.PartnerCommissionRewardRate) {
        return true
    }

    return false
}

// SetPartnerCommissionRewardRate gets a reference to the given int64 and assigns it to the PartnerCommissionRewardRate field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetPartnerCommissionRewardRate(v int64) {
    o.PartnerCommissionRewardRate = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetPrice() AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice {
    if o == nil || utils.IsNil(o.Price) {
        var ret AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice
        return ret
    }
    return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetPriceOk() (*AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice, bool) {
    if o == nil || utils.IsNil(o.Price) {
        return nil, false
    }
    return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasPrice() bool {
    if o != nil && !utils.IsNil(o.Price) {
        return true
    }

    return false
}

// SetPrice gets a reference to the given AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice and assigns it to the Price field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetPrice(v AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice) {
    o.Price = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetProductId() string {
    if o == nil || utils.IsNil(o.ProductId) {
        var ret string
        return ret
    }
    return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetProductIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ProductId) {
        return nil, false
    }
    return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasProductId() bool {
    if o != nil && !utils.IsNil(o.ProductId) {
        return true
    }

    return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetProductId(v string) {
    o.ProductId = &v
}

// GetProductName returns the ProductName field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetProductName() string {
    if o == nil || utils.IsNil(o.ProductName) {
        var ret string
        return ret
    }
    return *o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetProductNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ProductName) {
        return nil, false
    }
    return o.ProductName, true
}

// HasProductName returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasProductName() bool {
    if o != nil && !utils.IsNil(o.ProductName) {
        return true
    }

    return false
}

// SetProductName gets a reference to the given string and assigns it to the ProductName field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetProductName(v string) {
    o.ProductName = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetQuantity() int32 {
    if o == nil || utils.IsNil(o.Quantity) {
        var ret int32
        return ret
    }
    return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetQuantityOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Quantity) {
        return nil, false
    }
    return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasQuantity() bool {
    if o != nil && !utils.IsNil(o.Quantity) {
        return true
    }

    return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetQuantity(v int32) {
    o.Quantity = &v
}

// GetRefundedQuantity returns the RefundedQuantity field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetRefundedQuantity() int32 {
    if o == nil || utils.IsNil(o.RefundedQuantity) {
        var ret int32
        return ret
    }
    return *o.RefundedQuantity
}

// GetRefundedQuantityOk returns a tuple with the RefundedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetRefundedQuantityOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.RefundedQuantity) {
        return nil, false
    }
    return o.RefundedQuantity, true
}

// HasRefundedQuantity returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasRefundedQuantity() bool {
    if o != nil && !utils.IsNil(o.RefundedQuantity) {
        return true
    }

    return false
}

// SetRefundedQuantity gets a reference to the given int32 and assigns it to the RefundedQuantity field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetRefundedQuantity(v int32) {
    o.RefundedQuantity = &v
}

// GetReturnedQuantity returns the ReturnedQuantity field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetReturnedQuantity() int32 {
    if o == nil || utils.IsNil(o.ReturnedQuantity) {
        var ret int32
        return ret
    }
    return *o.ReturnedQuantity
}

// GetReturnedQuantityOk returns a tuple with the ReturnedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetReturnedQuantityOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.ReturnedQuantity) {
        return nil, false
    }
    return o.ReturnedQuantity, true
}

// HasReturnedQuantity returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasReturnedQuantity() bool {
    if o != nil && !utils.IsNil(o.ReturnedQuantity) {
        return true
    }

    return false
}

// SetReturnedQuantity gets a reference to the given int32 and assigns it to the ReturnedQuantity field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetReturnedQuantity(v int32) {
    o.ReturnedQuantity = &v
}

// GetTapCommissionRate returns the TapCommissionRate field value if set, zero value otherwise.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetTapCommissionRate() int64 {
    if o == nil || utils.IsNil(o.TapCommissionRate) {
        var ret int64
        return ret
    }
    return *o.TapCommissionRate
}

// GetTapCommissionRateOk returns a tuple with the TapCommissionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) GetTapCommissionRateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TapCommissionRate) {
        return nil, false
    }
    return o.TapCommissionRate, true
}

// HasTapCommissionRate returns a boolean if a field has been set.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) HasTapCommissionRate() bool {
    if o != nil && !utils.IsNil(o.TapCommissionRate) {
        return true
    }

    return false
}

// SetTapCommissionRate gets a reference to the given int64 and assigns it to the TapCommissionRate field.
func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) SetTapCommissionRate(v int64) {
    o.TapCommissionRate = &v
}

func (o AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ActualCommissionBase) {
        toSerialize["actual_commission_base"] = o.ActualCommissionBase
    }
    if !utils.IsNil(o.ActualCreatorCommission) {
        toSerialize["actual_creator_commission"] = o.ActualCreatorCommission
    }
    if !utils.IsNil(o.ActualCreatorCommissionRewardFee) {
        toSerialize["actual_creator_commission_reward_fee"] = o.ActualCreatorCommissionRewardFee
    }
    if !utils.IsNil(o.ActualPartnerCommissionRewardFee) {
        toSerialize["actual_partner_commission_reward_fee"] = o.ActualPartnerCommissionRewardFee
    }
    if !utils.IsNil(o.ActualTapCommission) {
        toSerialize["actual_tap_commission"] = o.ActualTapCommission
    }
    if !utils.IsNil(o.CampaignId) {
        toSerialize["campaign_id"] = o.CampaignId
    }
    if !utils.IsNil(o.ContentId) {
        toSerialize["content_id"] = o.ContentId
    }
    if !utils.IsNil(o.ContentType) {
        toSerialize["content_type"] = o.ContentType
    }
    if !utils.IsNil(o.CreatorCommissionRate) {
        toSerialize["creator_commission_rate"] = o.CreatorCommissionRate
    }
    if !utils.IsNil(o.CreatorCommissionRewardRate) {
        toSerialize["creator_commission_reward_rate"] = o.CreatorCommissionRewardRate
    }
    if !utils.IsNil(o.CreatorUsername) {
        toSerialize["creator_username"] = o.CreatorUsername
    }
    if !utils.IsNil(o.EstimatedCommissionBase) {
        toSerialize["estimated_commission_base"] = o.EstimatedCommissionBase
    }
    if !utils.IsNil(o.EstimatedCreatorCommission) {
        toSerialize["estimated_creator_commission"] = o.EstimatedCreatorCommission
    }
    if !utils.IsNil(o.EstimatedCreatorCommissionRewardFee) {
        toSerialize["estimated_creator_commission_reward_fee"] = o.EstimatedCreatorCommissionRewardFee
    }
    if !utils.IsNil(o.EstimatedPartnerCommissionRewardFee) {
        toSerialize["estimated_partner_commission_reward_fee"] = o.EstimatedPartnerCommissionRewardFee
    }
    if !utils.IsNil(o.EstimatedTapCommission) {
        toSerialize["estimated_tap_commission"] = o.EstimatedTapCommission
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.PartnerCommissionRewardRate) {
        toSerialize["partner_commission_reward_rate"] = o.PartnerCommissionRewardRate
    }
    if !utils.IsNil(o.Price) {
        toSerialize["price"] = o.Price
    }
    if !utils.IsNil(o.ProductId) {
        toSerialize["product_id"] = o.ProductId
    }
    if !utils.IsNil(o.ProductName) {
        toSerialize["product_name"] = o.ProductName
    }
    if !utils.IsNil(o.Quantity) {
        toSerialize["quantity"] = o.Quantity
    }
    if !utils.IsNil(o.RefundedQuantity) {
        toSerialize["refunded_quantity"] = o.RefundedQuantity
    }
    if !utils.IsNil(o.ReturnedQuantity) {
        toSerialize["returned_quantity"] = o.ReturnedQuantity
    }
    if !utils.IsNil(o.TapCommissionRate) {
        toSerialize["tap_commission_rate"] = o.TapCommissionRate
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) UnmarshalJSON(data []byte) (err error) {
    varAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus := _AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus{}

    err = json.Unmarshal(data, &varAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus)

    if err != nil {
        return err
    }

    *o = AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus(varAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "actual_commission_base")
        delete(additionalProperties, "actual_creator_commission")
        delete(additionalProperties, "actual_creator_commission_reward_fee")
        delete(additionalProperties, "actual_partner_commission_reward_fee")
        delete(additionalProperties, "actual_tap_commission")
        delete(additionalProperties, "campaign_id")
        delete(additionalProperties, "content_id")
        delete(additionalProperties, "content_type")
        delete(additionalProperties, "creator_commission_rate")
        delete(additionalProperties, "creator_commission_reward_rate")
        delete(additionalProperties, "creator_username")
        delete(additionalProperties, "estimated_commission_base")
        delete(additionalProperties, "estimated_creator_commission")
        delete(additionalProperties, "estimated_creator_commission_reward_fee")
        delete(additionalProperties, "estimated_partner_commission_reward_fee")
        delete(additionalProperties, "estimated_tap_commission")
        delete(additionalProperties, "id")
        delete(additionalProperties, "partner_commission_reward_rate")
        delete(additionalProperties, "price")
        delete(additionalProperties, "product_id")
        delete(additionalProperties, "product_name")
        delete(additionalProperties, "quantity")
        delete(additionalProperties, "refunded_quantity")
        delete(additionalProperties, "returned_quantity")
        delete(additionalProperties, "tap_commission_rate")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus struct {
	value *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus
	isSet bool
}

func (v NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) Get() *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus {
	return v.value
}

func (v *NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) Set(val *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus(val *AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) *NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus {
	return &NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus{value: val, isSet: true}
}

func (v NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


