/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202412

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202412GetConversationListRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202412GetConversationListRequestBody{}

// AffiliateSeller202412GetConversationListRequestBody struct for AffiliateSeller202412GetConversationListRequestBody
type AffiliateSeller202412GetConversationListRequestBody struct {
    // - If `true`, only `conversation_id` in `data.conversation` is returned.  - If `false`, all fields in `data.conversation` are returned. `true` by default.
    OnlyNeedConversationId *bool `json:"only_need_conversation_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202412GetConversationListRequestBody AffiliateSeller202412GetConversationListRequestBody

// NewAffiliateSeller202412GetConversationListRequestBody instantiates a new AffiliateSeller202412GetConversationListRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202412GetConversationListRequestBody() *AffiliateSeller202412GetConversationListRequestBody {
    this := AffiliateSeller202412GetConversationListRequestBody{}
    return &this
}

// NewAffiliateSeller202412GetConversationListRequestBodyWithDefaults instantiates a new AffiliateSeller202412GetConversationListRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202412GetConversationListRequestBodyWithDefaults() *AffiliateSeller202412GetConversationListRequestBody {
    this := AffiliateSeller202412GetConversationListRequestBody{}
    return &this
}

// GetOnlyNeedConversationId returns the OnlyNeedConversationId field value if set, zero value otherwise.
func (o *AffiliateSeller202412GetConversationListRequestBody) GetOnlyNeedConversationId() bool {
    if o == nil || utils.IsNil(o.OnlyNeedConversationId) {
        var ret bool
        return ret
    }
    return *o.OnlyNeedConversationId
}

// GetOnlyNeedConversationIdOk returns a tuple with the OnlyNeedConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202412GetConversationListRequestBody) GetOnlyNeedConversationIdOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.OnlyNeedConversationId) {
        return nil, false
    }
    return o.OnlyNeedConversationId, true
}

// HasOnlyNeedConversationId returns a boolean if a field has been set.
func (o *AffiliateSeller202412GetConversationListRequestBody) HasOnlyNeedConversationId() bool {
    if o != nil && !utils.IsNil(o.OnlyNeedConversationId) {
        return true
    }

    return false
}

// SetOnlyNeedConversationId gets a reference to the given bool and assigns it to the OnlyNeedConversationId field.
func (o *AffiliateSeller202412GetConversationListRequestBody) SetOnlyNeedConversationId(v bool) {
    o.OnlyNeedConversationId = &v
}

func (o AffiliateSeller202412GetConversationListRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202412GetConversationListRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.OnlyNeedConversationId) {
        toSerialize["only_need_conversation_id"] = o.OnlyNeedConversationId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202412GetConversationListRequestBody) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202412GetConversationListRequestBody := _AffiliateSeller202412GetConversationListRequestBody{}

    err = json.Unmarshal(data, &varAffiliateSeller202412GetConversationListRequestBody)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202412GetConversationListRequestBody(varAffiliateSeller202412GetConversationListRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "only_need_conversation_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202412GetConversationListRequestBody struct {
	value *AffiliateSeller202412GetConversationListRequestBody
	isSet bool
}

func (v NullableAffiliateSeller202412GetConversationListRequestBody) Get() *AffiliateSeller202412GetConversationListRequestBody {
	return v.value
}

func (v *NullableAffiliateSeller202412GetConversationListRequestBody) Set(val *AffiliateSeller202412GetConversationListRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202412GetConversationListRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202412GetConversationListRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202412GetConversationListRequestBody(val *AffiliateSeller202412GetConversationListRequestBody) *NullableAffiliateSeller202412GetConversationListRequestBody {
	return &NullableAffiliateSeller202412GetConversationListRequestBody{value: val, isSet: true}
}

func (v NullableAffiliateSeller202412GetConversationListRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202412GetConversationListRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


