/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202412

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule{}

// AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule struct for AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule
type AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule struct {
    // If true, free samples are provided to creators invited to the target collaboration group.
    HasFreeSample *bool `json:"has_free_sample,omitempty"`
    // If true, creators invited to the target collaboration are exempt from seller review and will automatically be approved for a free sample. Note that if has_free_sample=false, this field will not take effect.
    IsSampleApprovalExempt *bool `json:"is_sample_approval_exempt,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule

// NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule instantiates a new AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule() *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule {
    this := AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule{}
    return &this
}

// NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRuleWithDefaults instantiates a new AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRuleWithDefaults() *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule {
    this := AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule{}
    return &this
}

// GetHasFreeSample returns the HasFreeSample field value if set, zero value otherwise.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) GetHasFreeSample() bool {
    if o == nil || utils.IsNil(o.HasFreeSample) {
        var ret bool
        return ret
    }
    return *o.HasFreeSample
}

// GetHasFreeSampleOk returns a tuple with the HasFreeSample field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) GetHasFreeSampleOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.HasFreeSample) {
        return nil, false
    }
    return o.HasFreeSample, true
}

// HasHasFreeSample returns a boolean if a field has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) HasHasFreeSample() bool {
    if o != nil && !utils.IsNil(o.HasFreeSample) {
        return true
    }

    return false
}

// SetHasFreeSample gets a reference to the given bool and assigns it to the HasFreeSample field.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) SetHasFreeSample(v bool) {
    o.HasFreeSample = &v
}

// GetIsSampleApprovalExempt returns the IsSampleApprovalExempt field value if set, zero value otherwise.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) GetIsSampleApprovalExempt() bool {
    if o == nil || utils.IsNil(o.IsSampleApprovalExempt) {
        var ret bool
        return ret
    }
    return *o.IsSampleApprovalExempt
}

// GetIsSampleApprovalExemptOk returns a tuple with the IsSampleApprovalExempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) GetIsSampleApprovalExemptOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.IsSampleApprovalExempt) {
        return nil, false
    }
    return o.IsSampleApprovalExempt, true
}

// HasIsSampleApprovalExempt returns a boolean if a field has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) HasIsSampleApprovalExempt() bool {
    if o != nil && !utils.IsNil(o.IsSampleApprovalExempt) {
        return true
    }

    return false
}

// SetIsSampleApprovalExempt gets a reference to the given bool and assigns it to the IsSampleApprovalExempt field.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) SetIsSampleApprovalExempt(v bool) {
    o.IsSampleApprovalExempt = &v
}

func (o AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.HasFreeSample) {
        toSerialize["has_free_sample"] = o.HasFreeSample
    }
    if !utils.IsNil(o.IsSampleApprovalExempt) {
        toSerialize["is_sample_approval_exempt"] = o.IsSampleApprovalExempt
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule := _AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule{}

    err = json.Unmarshal(data, &varAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule(varAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "has_free_sample")
        delete(additionalProperties, "is_sample_approval_exempt")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule struct {
	value *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule
	isSet bool
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) Get() *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule {
	return v.value
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) Set(val *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule(val *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule {
	return &NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule{value: val, isSet: true}
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationFreeSampleRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


