/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202412

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202412QueryTargetCollaborationDetailResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202412QueryTargetCollaborationDetailResponseData{}

// AffiliateSeller202412QueryTargetCollaborationDetailResponseData struct for AffiliateSeller202412QueryTargetCollaborationDetailResponseData
type AffiliateSeller202412QueryTargetCollaborationDetailResponseData struct {
    TargetCollaboration *AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration `json:"target_collaboration,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202412QueryTargetCollaborationDetailResponseData AffiliateSeller202412QueryTargetCollaborationDetailResponseData

// NewAffiliateSeller202412QueryTargetCollaborationDetailResponseData instantiates a new AffiliateSeller202412QueryTargetCollaborationDetailResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202412QueryTargetCollaborationDetailResponseData() *AffiliateSeller202412QueryTargetCollaborationDetailResponseData {
    this := AffiliateSeller202412QueryTargetCollaborationDetailResponseData{}
    return &this
}

// NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataWithDefaults instantiates a new AffiliateSeller202412QueryTargetCollaborationDetailResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202412QueryTargetCollaborationDetailResponseDataWithDefaults() *AffiliateSeller202412QueryTargetCollaborationDetailResponseData {
    this := AffiliateSeller202412QueryTargetCollaborationDetailResponseData{}
    return &this
}

// GetTargetCollaboration returns the TargetCollaboration field value if set, zero value otherwise.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) GetTargetCollaboration() AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration {
    if o == nil || utils.IsNil(o.TargetCollaboration) {
        var ret AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration
        return ret
    }
    return *o.TargetCollaboration
}

// GetTargetCollaborationOk returns a tuple with the TargetCollaboration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) GetTargetCollaborationOk() (*AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration, bool) {
    if o == nil || utils.IsNil(o.TargetCollaboration) {
        return nil, false
    }
    return o.TargetCollaboration, true
}

// HasTargetCollaboration returns a boolean if a field has been set.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) HasTargetCollaboration() bool {
    if o != nil && !utils.IsNil(o.TargetCollaboration) {
        return true
    }

    return false
}

// SetTargetCollaboration gets a reference to the given AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration and assigns it to the TargetCollaboration field.
func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) SetTargetCollaboration(v AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration) {
    o.TargetCollaboration = &v
}

func (o AffiliateSeller202412QueryTargetCollaborationDetailResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202412QueryTargetCollaborationDetailResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.TargetCollaboration) {
        toSerialize["target_collaboration"] = o.TargetCollaboration
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202412QueryTargetCollaborationDetailResponseData := _AffiliateSeller202412QueryTargetCollaborationDetailResponseData{}

    err = json.Unmarshal(data, &varAffiliateSeller202412QueryTargetCollaborationDetailResponseData)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202412QueryTargetCollaborationDetailResponseData(varAffiliateSeller202412QueryTargetCollaborationDetailResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "target_collaboration")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData struct {
	value *AffiliateSeller202412QueryTargetCollaborationDetailResponseData
	isSet bool
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) Get() *AffiliateSeller202412QueryTargetCollaborationDetailResponseData {
	return v.value
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) Set(val *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData(val *AffiliateSeller202412QueryTargetCollaborationDetailResponseData) *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData {
	return &NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData{value: val, isSet: true}
}

func (v NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202412QueryTargetCollaborationDetailResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


