SET search_path TO tenant_yumna_bertigamart, public;

CREATE TABLE IF NOT EXISTS tiktok_ads_product_names (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    name TEXT,
    category VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

DELETE FROM tiktok_ads_product_names WHERE tenant_id = 'yumna_bertigamart';

INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733055736054318244', 'Nusseyba - Bahira Handshock - Handshock Jempol Jersey - Manset Tangan Fingerless', 'Handsock (601345)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733204152982930596', 'Nusseyba - Dzikra Top - Atasan Basic Batwing Daily Olahraga - Bahan Rayon Spande', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732476736733283492', 'Nusseyba - Khala Dress - Gamis Wanita Simple Daily - Bahan Combed - Dress Muslim', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731521780235338916', 'Nusseyba - Hana Khimar Bandana - Jersey Khiban 2in1  Wanita - Bergo Sporty Penut', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732318700109726884', 'Nusseyba - Bilya Skirt - Rok Olahraga Dry Fit - Sporty Skirt Muslimah - Rok Wani', 'Rok Olahraga (963720)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731365288154334372', 'Nusseyba - Arabella Khimar Bandana - Jersey Khiban 2in1 Haji Umroh - Bergo Sport', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730927911385138340', 'Nusseyba - Tazkiya Khimar Bandana - Khimar Handless - Arabeschi by Sultan- Khima', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732491544228955300', 'Nusseyba - Mika Bag - Tas Tenteng Mika Transparant - Tas Hampers Premium - Toteb', 'Tote Bag (903176)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732148829314057380', 'Nusseyba - Hilly Khimar Bandana - Khiban Dry Fit - Khiban 2in1 Size Medium -Khim', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730837831053247652', 'Nusseyba - Pashmina Instan Saila - Hijab Wanita Muslimah - Pastan Instan Nyaman ', 'Hijab Instan (601306)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730837898076783780', 'Nusseyba - Zia Khimar Bandana - Khimar Bandana Anti UV Thuba by Sultan - Khiban ', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731584842237969572', 'Nusseyba - Xavia Long Outer - Cardigan Simple Frea Knit - Atasan Basic Panjang -', 'Kardigan (601333)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733280430620968100', 'Nusseyba - Aira Dress - Gamis Wanita Bahan Katun Combed - Dress Daily Muslim Ker', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732089843750438052', 'Nusseyba - Azka Duffle Bag - Tas Travel Besar - Tas Portable Gym Hitam Fuchsia -', 'Tas Olahraga (603682)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730839323869545636', 'Nusseyba - Emir Thobe Jubah - Bahan Tencel Poplin - Jubbah Umroh Pria Dewasa - G', 'Jubah (601327)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730967787063248036', 'Nusseyba - Tumbler Arizona - Tumbler Stainless Steel 500ml - Termos Vakum - Boto', 'Botol Air (600048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730860603486340260', 'Nusseyba - Ghava Kurta - Koko Umroh Dewasa - Pakaian Muslim Pria - Atasan Lengan', 'Baju Koko & Atasan (601326)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730916635828520100', 'Nusseyba - Haniya Dress - Bahan Milwauke - Gamis Lebaran - Koleksi Raya Collecti', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732627617799701668', 'Nusseyba - Teeqa Niqob - Cadar Bandana - Niqob Basic Kerudung - Cadar Poni - Ban', 'Cadar (803984)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733628052324844708', 'Nusseyba - Tahira Stripe Top - Baju Kaos Wanita Lengan Panjang - Atasan Stripe B', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732627415721477284', 'Nusseyba - Saba Niqob - Cadar Bandana - Dua Layer - Premium Jahitan lokal - Baha', 'Cadar (803984)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731901363564741796', 'Nusseyba - Taza Skirt - Rok Celana Dry Fit - Bawahan Olahraga Wanita - Rokcel Pa', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732392530511168676', 'Nusseyba - Danish Jacket - Jaket Parasut Syari Ringan Anti Angin - Outer Olahrag', 'Jaket (601334)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732947580497003684', 'Nusseyba - Laiba Vest - Top Only Parasute Micro - Pakain Wanita Muslimah Trendy ', 'Waistcoat (601332)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733712966997607588', 'Nusseyba - Cayra Visor - Topi Olahraga Wanita - Protection Sports Visor Hat - To', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733751830798959780', 'Nusseyba - Faima Cadar - Niqob Bahan Arabian Beauty - Cadar Tali Karet Daily Ant', 'Cadar (803984)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733020180288341156', 'Nusseyba - Aghnia Skirt- Rok Olahraga Bahan Dry Fit - Bawahan Wanita Muslimah Sp', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730968137870509220', 'Nusseyba - Sejadah Travel Tivana - Sajadah Souvenir Umrah - Gift Haji dan Umroh ', 'Sajadah (601351)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732318534200427684', 'Nusseyba - Bilya Top - Atasan Baju Olahraga Wanita Dry Fit - Tunik Sporty Muslim', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730839287144350884', 'Nusseyba - Ghania Dress -  Bahan Tulle Premium - Dress Wanita Mewah Elegant - Bu', 'Gaun (935816)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732628005846353060', 'Nusseyba - Shahira Niqob - Cadar Karet Dua Layer Jet Black - Bahan Shiffon Arabe', 'Cadar (803984)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732553333738144932', 'Nusseyba - Aghnia Top - Atasan Baju Olahraga - Pakaian Sporty Wanita Muslimah - ', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733373585495458980', 'Nusseyba - Thuraya Pashban - Pashmina Bandana Bahan Jersey ITY - Hijab Instan Sy', 'Hijab Instan (601306)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733090775852614820', 'Nusseyba - Afra Handshock - Handshock Basic Jersey - Manset Tangan Syar''i Muslim', 'Handsock (601345)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733711532794217636', 'Nusseyba - Keira Pleats Skirt - Rok Plisket Bahan Dri Fit Premium - Plisket Panj', 'Rok (601316)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732148580878222500', 'Nusseyba - Itsar Khiban - Khimar Bandana Dry Fit - Long Khiban 2in1 -Khimar Inst', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733120831405393060', 'Nusseyba - Mireya Skirt - Rok Wanita Parasut Crinkle - Bawahan Olahraga Nyaman R', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731182209200391332', 'Nusseyba - Syafira Outer - Long Outer Wanita - Outer Muslimah Nyaman Mewah 2in1 ', 'Kardigan (601333)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733120391580058788', 'Nusseyba - Mireya Jacket - Jaket Outdoor Parasut Wanita -  Jaket Serut Olahraga ', 'Jaket (601334)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732780482394490020', 'Nusseyba - Adiba Jacket - Jaket Parka Wanita Waterproof Windproof - Jaket Parasu', 'Jaket (601334)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730968379527300260', 'Nusseyba - Box Hampers Raya - Packaging Hampers Pakaian - Dus Kado Lebaran - Ham', 'Hadiah & Pembungkus (832136)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730927265359299748', 'Nusseyba - Nadia Khimar Bandana - Khiban Syari Bahan Milwauke - Khimar Bergo 2in', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730812714099377316', 'Nusseyba - Kirana Prayer - Mukena Terusan Wanita Eksklusif - Mukenah Malaysia Pr', 'Mukena (838792)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731306059359290532', 'Nusseyba - Wafiyya Set Sporty - Jaket & Rok Wanita Parasut - Skirt Olahraga Nyam', 'Luaran & Hoodie Olahraga (603706)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733752159013864612', 'Nusseyba - Ezlyn Cadar - Niqob Bahan Arabian Beauty - Cadar Tali Karet Daily Ant', 'Cadar (803984)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1731899200566232228', 'Nusseyba - Taza Kaos Dry Fit - Baju Olahraga Lengan Panjang - Pakaian Sport Wani', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732205670702154916', 'Nusseyba Flor Active Parfum & Deospray For Women - Parfume Wanita Royal Fragranc', 'Parfum Wanita (855952)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733902411361191076', 'Nusseyba - Fashy Long Jacket - Bahan Terry Embossed - Long Jaket Muslimah - Jake', 'Jaket (601334)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1733811158603039908', 'Nusseyba - Emira Jacket - Jaket Wanita Comfy Zipper Korean Style - Sweater Bahan', 'Jaket (601334)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1732475596305892516', 'Nusseyba - Yuurra Dress - Gamis Wanita Simple Daily - Bahan Combed Pique Diamond', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730446436005086372', 'Nusseyba - Naqeeya Dress - Gamis Muslim Syari - Bahan Katun Combed - Outfit  Ata', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730227817144878244', 'Nusseyba - Syakila French Khimar - Hijab Instan Syari Jarsey ITY Premium - Outfi', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729593229837568164', 'Nusseyba - Chessy Handsock Panjang - Manset Muslim - Manset Tangan Wanita Hitam', 'Handsock (601345)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729600650196977828', 'Nusseyba - Sarah French Khimar - Jilbab Syari Panjang - Kerudung Bergo Hitam Ins', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729839871380653220', 'Nusseyba - Syakila French Khimar - Hijab Instan Syari Jarsey ITY Premium - Outfi', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730448467452069028', 'Nusseyba - Husna French Khimar - Jersey ITY FK Syari - French Khimar Instan - Hi', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729980642487797924', 'Nusseyba - Sofa Inner - Ciput Hijab Anti Pusing - Fashion Muslimah - Jersey Prem', 'Ciput (601305)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730320664646223012', 'Nusseyba - Hazeera Long Jacket - Bahan Terry Embossed - Jaket Muslim Panjang - C', 'Jaket & Mantel (601267)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729732509484222628', 'Nusseyba - Syakila French Khimar - Hijab Instan Syari Jarsey ITY Premium - Outfi', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729732503017851044', 'Nusseyba  - Anisah Khimar - Hijab Instan Crinkle - Kerudung Muslim Airflow - Hij', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730590677613773988', 'Nusseyba - Zalfa Dress - Bahan Knit Mewah - Gamis Lebaran Muslim Wanita  - Gamis', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730446350206600356', 'Nusseyba - Rubina Top - Atasan Dryfit - Outfit Olahraga Celana - Baju Polos Olah', 'Kaos Olahraga (835720)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730180613702845604', 'Nusseyba - Ghaliya Skirt - Rok Celana Bahan Chamomile - Rok Celana Setelan Olahr', 'Rok Olahraga (963720)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729767299017376932', 'Nusseyba - Inayah Hat - Topi Haji dan Umroh  - Topi Pantai  dewasa -Topi Umrah W', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729601167041136804', 'Nusseyba - Chafika Bucket Hat - Topi Umrah Dewasa - Topi Bucket Cantik Elegan - ', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730228438133802148', 'Nusseyba - Basma Cap - Topi Baseball Cap Unisex - Topi Baseball Pria Wanita - Ou', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729983436607030436', 'Nusseyba - Yaffa Khimar Instan - Kerudung Jersey  ITY Premium - Bergo Sporty - H', 'Hijab Instan (601306)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729582375418038436', 'Nusseyba - Huri Skirt - Rok Celana Muslim - Outfit Sporty Dewasa - Setelan Olahr', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730228114064049316', 'Nusseyba - Sofa Inner - Ciput Hijab Anti Pusing- Dalaman Kerudung Instan - Inner', 'Ciput (601305)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729691467773019300', 'Nusseyba - Aisyah Dress - Abaya Muslim Syari - Gamis Basic Wanita Simple - Crink', 'Abaya (601323)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729640048694233252', 'Nusseyba - Ifana Bucket Hat - Topi Rimba Gunung - Muslim Nyaman Uniseks - Topi O', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729620247744251044', 'Nusseyba - Basma Cap - Topi Baseball Unisex - Topi Pria Wanita  Outdoor  - Topi ', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729607174444647588', 'Nusseyba - Ashadiya Jacket - Jaket Parasut Olahraga - Jacket Outer Parasut - Jak', 'Luaran & Hoodie Olahraga (603706)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729611730822988964', 'Nusseyba - Adha Cross Bag - Tas Kajian - Tas Pouch Mini - Tas Selempang -   Slin', 'Tas Selempang & Bahu (601429)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729568539639580836', 'Nusseyba - Zakiy Jubbah - Pakaian Umroh laki-laki - Muslim Jubah Dewasa - Gamis ', 'Jubah (601327)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730228552431600804', 'Nusseyba - Mazna Bucket - Topi Rimba Gunung - Topi Outdoor Uniseks - Topi Olahra', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730395889207772324', 'Nusseyba - Alika Top - Atasan Olahraga Wanita Polos - Pakaian Muslim Panjang - B', 'Kaos Olahraga (835720)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730441405228483748', 'Nusseyba - Scrunchie Hijab Mini - Ikat Rambut - Cepol Hijab - Kunciran Harian Sa', 'Ikat Rambut & Scrunchie (908424)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730446590134355108', 'Nusseyba - Adreena Dress - Bahan Combed Pique Diamond - Outfit Lebaran Dewasa  -', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729583837157427364', 'Nusseyba - Fida Top - Atasan Sport Wanita - Kaos Olahraga Wanita - Kaos Olahraga', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729620355214378148', 'Nusseyba - Mazna Bucket - Topi Rimba Gunung - Muslim Outdoor Nyaman - Topi Olahr', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729943550833100964', 'Nusseyba - Vazza Inner Basic - Ciput Hijab - Inner Kerudung Anti Pusing -  Dalam', 'Ciput (601305)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730184555857413284', 'Nusseyba - Elina Skirt - Rok Plisket Premium - Pleats Skirt Panjang - Rok Hitam ', 'Rok (601264)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730228415053005988', 'Nusseyba - Inayah Hat - Topi Haji dan Umroh Wanita - Topi Umrah Dewasa - Topi  P', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730699282480661668', 'Nusseyba - Kaluna Backpack - Tas Travel Stylish - Tas Ransel Multifungsi Wanita ', 'Ransel (601446)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730228515789112484', 'Nusseyba - Chafika Bucket Hat - Topi Umrah Wanita - Topi Bucket Mewah - Topi Umr', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730734412735349924', 'Nusseyba - Jennaira Prayer - Mukena Terusan Malaysia Eksklusif - Mukenah Malaysi', 'Mukena (838792)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729841333542945956', 'Nusseyba - Sofa Inner - Ciput Hijab Anti Pusing - Dalaman Kerudung Instan - Inne', 'Ciput (601305)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729664611806972068', 'Nusseyba - Adreena Dress - Bahan Combed Pique Diamond - Outfit Muslim Syari  Mew', 'Gamis (936072)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729943472583248036', 'Nusseyba - Zakiy Jubbah - Jubah Pria Dewasa - Gamis Muslim laki-laki - Jubah Umr', 'Jubah (601327)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729996619938236580', 'Nusseyba - Rubina Top - Atasan Dryfit - Outfit Olahraga Muslim - Baju Polos Olah', 'Kaos Olahraga (835720)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729600652879300772', 'Nusseyba - Fadhila Visor - Topi Golf - Visor Outdoor - Topi Pria Wanita - Topi G', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729857632157534372', 'Nusseyba - Kaina Hijab - Jilbab Crinkle Airflow - Kerudung Panjang Wanita - Keru', 'Hijab Instan (601306)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730227776661783716', 'Nusseyba - Ishana Bucket- Topi Umroh Wanita - Topi Haji dan Umrah - Outfit Ke Pa', 'Topi Olahraga & Outdoor (603654)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729679829877688484', 'Nusseyba - Raffasya Jubbah - Jubah Umroh Pria - Gamis Muslim Pria - Gamis Ikhwan', 'Jubah (601327)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730483625184953508', 'Nusseyba - Husna French Khimar - Jersey ITY FK Syari - French Khimar Instan - Hi', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729583836961081508', 'Nusseyba - Zahiya Skirt - Rok Celana Jogger Sporty - Outfit Olahraga Wanita syar', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1730446397466444964', 'Nusseyba - Zahiya Skirt - Rok Celana Jogger Sporty - Outfit Olahraga Wanita syar', 'Baju Olahraga Muslim (839048)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729567448038279332', 'Nusseyba - Jihan Niqob - Cadar Tali Ceruty Instan - Cadar Polos Dewasa - Khimar ', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729943570882594980', 'Nusseyba - Fayla Inner Basic - Ciput Hijab - Iner  Kerudung Anti Pusing Anti Bud', 'Ciput (601305)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566713181799588', 'Nusseyba - Pulpen Kajian NSYB - Retreactable Gel Pen Cair 0,5mm - Perlengkapan K', 'Alat Tulis & Koreksi (603002)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566104157979812', 'Nusseyba - Haafiz Kurta - Cotton Madina Premium - Koko Umroh Pria Dewasa - Atasa', 'Baju Koko & Atasan (601326)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729476857785452708', 'Nusseyba - Naqeeya Dress - Gamis Syari Dewasa - Katun Combed - Outfit Lebaran Me', 'Gaun (935816)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729511392877709476', 'Nusseyba - Ishana Bucket Hat - Topi Umrah Wanita - Topi Haji dan Umrah - Outfit ', 'Topi (906248)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566155700667556', 'Nusseyba - Khimar Care Spray - Linen Spray - Pengharum Pakaian - Parfum - Non Al', 'Parfum Wanita (855952)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566837642003620', 'Nusseyba - Notebook NSYB - Buku Catatan - Buku Diary Jurnal Harian - Paper Stati', 'Notebook & Kertas (831880)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566022195774628', 'Nusseyba - Alesha French Khimar - Mazen Anti UV Sultan - Jilbab Antem Syar''i - F', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729566162695455908', 'Nusseyba - Box Hampers Hijab - Packaging Hampers - Karton Packing', 'Perangkat Sholat (601350)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729479847524010148', 'Nusseyba - Almira French Khimar Set - Crinkle Airflow - Setelan Premium Wanita -', 'Khimar (601309)', NOW(), NOW());
INSERT INTO tiktok_ads_product_names (tenant_id, product_id, name, category, created_at, updated_at) VALUES ('yumna_bertigamart', '1729544953681381540', 'Nusseyba - Veeya Khimar Instan - Hijab Syari Wanita - Bahan Crincle Airflow - Ke', 'Khimar (601309)', NOW(), NOW());

SELECT COUNT(*) as total_imported FROM tiktok_ads_product_names;