/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule{}

// AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule struct for AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule
type AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule struct {
    // If set to `true`, free samples are provided to creators invited to the target collaboration group. If set to `false`, free samples are not provided.
    HasFreeSample *bool `json:"has_free_sample,omitempty"`
    // If set to `true`, creators invited to the target collaboration are exempt from seller review and are automatically approved for a free  product sample. Note that the `has_free_sample` property overrides the free sample behavior. 
    IsSampleApprovalExempt *bool `json:"is_sample_approval_exempt,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule

// NewAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule instantiates a new AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule() *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
    this := AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule{}
    return &this
}

// NewAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRuleWithDefaults instantiates a new AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRuleWithDefaults() *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
    this := AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule{}
    return &this
}

// GetHasFreeSample returns the HasFreeSample field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) GetHasFreeSample() bool {
    if o == nil || utils.IsNil(o.HasFreeSample) {
        var ret bool
        return ret
    }
    return *o.HasFreeSample
}

// GetHasFreeSampleOk returns a tuple with the HasFreeSample field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) GetHasFreeSampleOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.HasFreeSample) {
        return nil, false
    }
    return o.HasFreeSample, true
}

// HasHasFreeSample returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) HasHasFreeSample() bool {
    if o != nil && !utils.IsNil(o.HasFreeSample) {
        return true
    }

    return false
}

// SetHasFreeSample gets a reference to the given bool and assigns it to the HasFreeSample field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) SetHasFreeSample(v bool) {
    o.HasFreeSample = &v
}

// GetIsSampleApprovalExempt returns the IsSampleApprovalExempt field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) GetIsSampleApprovalExempt() bool {
    if o == nil || utils.IsNil(o.IsSampleApprovalExempt) {
        var ret bool
        return ret
    }
    return *o.IsSampleApprovalExempt
}

// GetIsSampleApprovalExemptOk returns a tuple with the IsSampleApprovalExempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) GetIsSampleApprovalExemptOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.IsSampleApprovalExempt) {
        return nil, false
    }
    return o.IsSampleApprovalExempt, true
}

// HasIsSampleApprovalExempt returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) HasIsSampleApprovalExempt() bool {
    if o != nil && !utils.IsNil(o.IsSampleApprovalExempt) {
        return true
    }

    return false
}

// SetIsSampleApprovalExempt gets a reference to the given bool and assigns it to the IsSampleApprovalExempt field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) SetIsSampleApprovalExempt(v bool) {
    o.IsSampleApprovalExempt = &v
}

func (o AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.HasFreeSample) {
        toSerialize["has_free_sample"] = o.HasFreeSample
    }
    if !utils.IsNil(o.IsSampleApprovalExempt) {
        toSerialize["is_sample_approval_exempt"] = o.IsSampleApprovalExempt
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule := _AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule{}

    err = json.Unmarshal(data, &varAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule(varAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "has_free_sample")
        delete(additionalProperties, "is_sample_approval_exempt")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule struct {
	value *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule
	isSet bool
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) Get() *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
	return v.value
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) Set(val *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule(val *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) *NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
	return &NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


