/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405CreateTargetCollaborationRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405CreateTargetCollaborationRequestBody{}

// AffiliateSeller202405CreateTargetCollaborationRequestBody struct for AffiliateSeller202405CreateTargetCollaborationRequestBody
type AffiliateSeller202405CreateTargetCollaborationRequestBody struct {
    // A list of TikTok user identifiers to invite to the target collaboration. Maximum length of the list is `50` user identifiers. 
    CreatorUserIds []string `json:"creator_user_ids,omitempty"`
    // The date at which the target collaboration ends, in Unix epoch time.
    EndTime *string `json:"end_time,omitempty"`
    FreeSampleRule *AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule `json:"free_sample_rule,omitempty"`
    // The message sent to creators associated with the target collaboration.
    Message *string `json:"message,omitempty"`
    // The name of the target collaboration.
    Name *string `json:"name,omitempty"`
    // A list of metadata and data for the products provided by the seller for target collaboration. Maximum length of the list is `100` products. 
    Products []AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts `json:"products,omitempty"`
    SellerContactInfo *AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo `json:"seller_contact_info,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202405CreateTargetCollaborationRequestBody AffiliateSeller202405CreateTargetCollaborationRequestBody

// NewAffiliateSeller202405CreateTargetCollaborationRequestBody instantiates a new AffiliateSeller202405CreateTargetCollaborationRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405CreateTargetCollaborationRequestBody() *AffiliateSeller202405CreateTargetCollaborationRequestBody {
    this := AffiliateSeller202405CreateTargetCollaborationRequestBody{}
    return &this
}

// NewAffiliateSeller202405CreateTargetCollaborationRequestBodyWithDefaults instantiates a new AffiliateSeller202405CreateTargetCollaborationRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405CreateTargetCollaborationRequestBodyWithDefaults() *AffiliateSeller202405CreateTargetCollaborationRequestBody {
    this := AffiliateSeller202405CreateTargetCollaborationRequestBody{}
    return &this
}

// GetCreatorUserIds returns the CreatorUserIds field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetCreatorUserIds() []string {
    if o == nil || utils.IsNil(o.CreatorUserIds) {
        var ret []string
        return ret
    }
    return o.CreatorUserIds
}

// GetCreatorUserIdsOk returns a tuple with the CreatorUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetCreatorUserIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.CreatorUserIds) {
        return nil, false
    }
    return o.CreatorUserIds, true
}

// HasCreatorUserIds returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasCreatorUserIds() bool {
    if o != nil && !utils.IsNil(o.CreatorUserIds) {
        return true
    }

    return false
}

// SetCreatorUserIds gets a reference to the given []string and assigns it to the CreatorUserIds field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetCreatorUserIds(v []string) {
    o.CreatorUserIds = v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetEndTime() string {
    if o == nil || utils.IsNil(o.EndTime) {
        var ret string
        return ret
    }
    return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetEndTimeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.EndTime) {
        return nil, false
    }
    return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasEndTime() bool {
    if o != nil && !utils.IsNil(o.EndTime) {
        return true
    }

    return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetEndTime(v string) {
    o.EndTime = &v
}

// GetFreeSampleRule returns the FreeSampleRule field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetFreeSampleRule() AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
    if o == nil || utils.IsNil(o.FreeSampleRule) {
        var ret AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule
        return ret
    }
    return *o.FreeSampleRule
}

// GetFreeSampleRuleOk returns a tuple with the FreeSampleRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetFreeSampleRuleOk() (*AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule, bool) {
    if o == nil || utils.IsNil(o.FreeSampleRule) {
        return nil, false
    }
    return o.FreeSampleRule, true
}

// HasFreeSampleRule returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasFreeSampleRule() bool {
    if o != nil && !utils.IsNil(o.FreeSampleRule) {
        return true
    }

    return false
}

// SetFreeSampleRule gets a reference to the given AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule and assigns it to the FreeSampleRule field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetFreeSampleRule(v AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule) {
    o.FreeSampleRule = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetMessage(v string) {
    o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetName(v string) {
    o.Name = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetProducts() []AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts {
    if o == nil || utils.IsNil(o.Products) {
        var ret []AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts
        return ret
    }
    return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetProductsOk() ([]AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts, bool) {
    if o == nil || utils.IsNil(o.Products) {
        return nil, false
    }
    return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasProducts() bool {
    if o != nil && !utils.IsNil(o.Products) {
        return true
    }

    return false
}

// SetProducts gets a reference to the given []AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts and assigns it to the Products field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetProducts(v []AffiliateSeller202405CreateTargetCollaborationRequestBodyProducts) {
    o.Products = v
}

// GetSellerContactInfo returns the SellerContactInfo field value if set, zero value otherwise.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetSellerContactInfo() AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo {
    if o == nil || utils.IsNil(o.SellerContactInfo) {
        var ret AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo
        return ret
    }
    return *o.SellerContactInfo
}

// GetSellerContactInfoOk returns a tuple with the SellerContactInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) GetSellerContactInfoOk() (*AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo, bool) {
    if o == nil || utils.IsNil(o.SellerContactInfo) {
        return nil, false
    }
    return o.SellerContactInfo, true
}

// HasSellerContactInfo returns a boolean if a field has been set.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) HasSellerContactInfo() bool {
    if o != nil && !utils.IsNil(o.SellerContactInfo) {
        return true
    }

    return false
}

// SetSellerContactInfo gets a reference to the given AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo and assigns it to the SellerContactInfo field.
func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) SetSellerContactInfo(v AffiliateSeller202405CreateTargetCollaborationRequestBodySellerContactInfo) {
    o.SellerContactInfo = &v
}

func (o AffiliateSeller202405CreateTargetCollaborationRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405CreateTargetCollaborationRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CreatorUserIds) {
        toSerialize["creator_user_ids"] = o.CreatorUserIds
    }
    if !utils.IsNil(o.EndTime) {
        toSerialize["end_time"] = o.EndTime
    }
    if !utils.IsNil(o.FreeSampleRule) {
        toSerialize["free_sample_rule"] = o.FreeSampleRule
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }
    if !utils.IsNil(o.Products) {
        toSerialize["products"] = o.Products
    }
    if !utils.IsNil(o.SellerContactInfo) {
        toSerialize["seller_contact_info"] = o.SellerContactInfo
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202405CreateTargetCollaborationRequestBody) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202405CreateTargetCollaborationRequestBody := _AffiliateSeller202405CreateTargetCollaborationRequestBody{}

    err = json.Unmarshal(data, &varAffiliateSeller202405CreateTargetCollaborationRequestBody)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202405CreateTargetCollaborationRequestBody(varAffiliateSeller202405CreateTargetCollaborationRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "creator_user_ids")
        delete(additionalProperties, "end_time")
        delete(additionalProperties, "free_sample_rule")
        delete(additionalProperties, "message")
        delete(additionalProperties, "name")
        delete(additionalProperties, "products")
        delete(additionalProperties, "seller_contact_info")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202405CreateTargetCollaborationRequestBody struct {
	value *AffiliateSeller202405CreateTargetCollaborationRequestBody
	isSet bool
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) Get() *AffiliateSeller202405CreateTargetCollaborationRequestBody {
	return v.value
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) Set(val *AffiliateSeller202405CreateTargetCollaborationRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405CreateTargetCollaborationRequestBody(val *AffiliateSeller202405CreateTargetCollaborationRequestBody) *NullableAffiliateSeller202405CreateTargetCollaborationRequestBody {
	return &NullableAffiliateSeller202405CreateTargetCollaborationRequestBody{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405CreateTargetCollaborationRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


