/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405SearchSellerAffiliateOrdersResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405SearchSellerAffiliateOrdersResponseData{}

// AffiliateSeller202405SearchSellerAffiliateOrdersResponseData struct for AffiliateSeller202405SearchSellerAffiliateOrdersResponseData
type AffiliateSeller202405SearchSellerAffiliateOrdersResponseData struct {
    // Next page token
    NextPageToken *string `json:"next_page_token,omitempty"`
    // Order information
    Orders []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders `json:"orders,omitempty"`
    // Total count of main orders that meet the query criteria.
    TotalCount *int64 `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202405SearchSellerAffiliateOrdersResponseData AffiliateSeller202405SearchSellerAffiliateOrdersResponseData

// NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseData instantiates a new AffiliateSeller202405SearchSellerAffiliateOrdersResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseData() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData {
    this := AffiliateSeller202405SearchSellerAffiliateOrdersResponseData{}
    return &this
}

// NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataWithDefaults instantiates a new AffiliateSeller202405SearchSellerAffiliateOrdersResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataWithDefaults() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData {
    this := AffiliateSeller202405SearchSellerAffiliateOrdersResponseData{}
    return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetOrders() []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders {
    if o == nil || utils.IsNil(o.Orders) {
        var ret []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders
        return ret
    }
    return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetOrdersOk() ([]AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders, bool) {
    if o == nil || utils.IsNil(o.Orders) {
        return nil, false
    }
    return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) HasOrders() bool {
    if o != nil && !utils.IsNil(o.Orders) {
        return true
    }

    return false
}

// SetOrders gets a reference to the given []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders and assigns it to the Orders field.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) SetOrders(v []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) {
    o.Orders = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetTotalCount() int64 {
    if o == nil || utils.IsNil(o.TotalCount) {
        var ret int64
        return ret
    }
    return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) GetTotalCountOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.TotalCount) {
        return nil, false
    }
    return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) HasTotalCount() bool {
    if o != nil && !utils.IsNil(o.TotalCount) {
        return true
    }

    return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) SetTotalCount(v int64) {
    o.TotalCount = &v
}

func (o AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.Orders) {
        toSerialize["orders"] = o.Orders
    }
    if !utils.IsNil(o.TotalCount) {
        toSerialize["total_count"] = o.TotalCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202405SearchSellerAffiliateOrdersResponseData := _AffiliateSeller202405SearchSellerAffiliateOrdersResponseData{}

    err = json.Unmarshal(data, &varAffiliateSeller202405SearchSellerAffiliateOrdersResponseData)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202405SearchSellerAffiliateOrdersResponseData(varAffiliateSeller202405SearchSellerAffiliateOrdersResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "orders")
        delete(additionalProperties, "total_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData struct {
	value *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData
	isSet bool
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) Get() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData {
	return v.value
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) Set(val *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData(val *AffiliateSeller202405SearchSellerAffiliateOrdersResponseData) *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData {
	return &NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


