/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders{}

// AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders struct for AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders
type AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders struct {
    // Main order identifier ID
    Id *string `json:"id,omitempty"`
    // Line item info list
    LineItems []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems `json:"line_items,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders

// NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders instantiates a new AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders {
    this := AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders{}
    return &this
}

// NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersWithDefaults instantiates a new AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersWithDefaults() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders {
    this := AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) SetId(v string) {
    o.Id = &v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) GetLineItems() []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems {
    if o == nil || utils.IsNil(o.LineItems) {
        var ret []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems
        return ret
    }
    return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) GetLineItemsOk() ([]AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems, bool) {
    if o == nil || utils.IsNil(o.LineItems) {
        return nil, false
    }
    return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) HasLineItems() bool {
    if o != nil && !utils.IsNil(o.LineItems) {
        return true
    }

    return false
}

// SetLineItems gets a reference to the given []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems and assigns it to the LineItems field.
func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) SetLineItems(v []AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrdersLineItems) {
    o.LineItems = v
}

func (o AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.LineItems) {
        toSerialize["line_items"] = o.LineItems
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders := _AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders{}

    err = json.Unmarshal(data, &varAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders(varAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "line_items")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders struct {
	value *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders
	isSet bool
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) Get() *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders {
	return v.value
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) Set(val *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders(val *AffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders {
	return &NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405SearchSellerAffiliateOrdersResponseDataOrders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


