/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission{}

// AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission struct for AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission
type AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission struct {
    // The commission amount. 
    Amount *string `json:"amount,omitempty"`
    // The currency code.
    Currency *string `json:"currency,omitempty"`
    // The commission rate in hundredths of a percent. For example, `3587` is a commission rate of `35.87%`. This value must a minimum of `1000`. 
    Rate *int64 `json:"rate,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission

// NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission instantiates a new AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission {
    this := AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission{}
    return &this
}

// NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommissionWithDefaults instantiates a new AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommissionWithDefaults() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission {
    this := AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) SetCurrency(v string) {
    o.Currency = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetRate() int64 {
    if o == nil || utils.IsNil(o.Rate) {
        var ret int64
        return ret
    }
    return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) GetRateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Rate) {
        return nil, false
    }
    return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) HasRate() bool {
    if o != nil && !utils.IsNil(o.Rate) {
        return true
    }

    return false
}

// SetRate gets a reference to the given int64 and assigns it to the Rate field.
func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) SetRate(v int64) {
    o.Rate = &v
}

func (o AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }
    if !utils.IsNil(o.Rate) {
        toSerialize["rate"] = o.Rate
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission := _AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission{}

    err = json.Unmarshal(data, &varAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission(varAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        delete(additionalProperties, "rate")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission struct {
	value *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission
	isSet bool
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) Get() *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission {
	return v.value
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) Set(val *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission(val *AffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission {
	return &NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission{value: val, isSet: true}
}

func (v NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202405SellerSearchAffiliateOpenCollaborationProductResponseDataProductsCommission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


