/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_v202402

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Affiliate202402CheckAnchorPrerequisitesRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Affiliate202402CheckAnchorPrerequisitesRequestBody{}

// Affiliate202402CheckAnchorPrerequisitesRequestBody struct for Affiliate202402CheckAnchorPrerequisitesRequestBody
type Affiliate202402CheckAnchorPrerequisitesRequestBody struct {
    // Product id that wanted to been checked.
    ProductId *string `json:"product_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Affiliate202402CheckAnchorPrerequisitesRequestBody Affiliate202402CheckAnchorPrerequisitesRequestBody

// NewAffiliate202402CheckAnchorPrerequisitesRequestBody instantiates a new Affiliate202402CheckAnchorPrerequisitesRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliate202402CheckAnchorPrerequisitesRequestBody() *Affiliate202402CheckAnchorPrerequisitesRequestBody {
    this := Affiliate202402CheckAnchorPrerequisitesRequestBody{}
    return &this
}

// NewAffiliate202402CheckAnchorPrerequisitesRequestBodyWithDefaults instantiates a new Affiliate202402CheckAnchorPrerequisitesRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliate202402CheckAnchorPrerequisitesRequestBodyWithDefaults() *Affiliate202402CheckAnchorPrerequisitesRequestBody {
    this := Affiliate202402CheckAnchorPrerequisitesRequestBody{}
    return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *Affiliate202402CheckAnchorPrerequisitesRequestBody) GetProductId() string {
    if o == nil || utils.IsNil(o.ProductId) {
        var ret string
        return ret
    }
    return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Affiliate202402CheckAnchorPrerequisitesRequestBody) GetProductIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ProductId) {
        return nil, false
    }
    return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *Affiliate202402CheckAnchorPrerequisitesRequestBody) HasProductId() bool {
    if o != nil && !utils.IsNil(o.ProductId) {
        return true
    }

    return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *Affiliate202402CheckAnchorPrerequisitesRequestBody) SetProductId(v string) {
    o.ProductId = &v
}

func (o Affiliate202402CheckAnchorPrerequisitesRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Affiliate202402CheckAnchorPrerequisitesRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ProductId) {
        toSerialize["product_id"] = o.ProductId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Affiliate202402CheckAnchorPrerequisitesRequestBody) UnmarshalJSON(data []byte) (err error) {
    varAffiliate202402CheckAnchorPrerequisitesRequestBody := _Affiliate202402CheckAnchorPrerequisitesRequestBody{}

    err = json.Unmarshal(data, &varAffiliate202402CheckAnchorPrerequisitesRequestBody)

    if err != nil {
        return err
    }

    *o = Affiliate202402CheckAnchorPrerequisitesRequestBody(varAffiliate202402CheckAnchorPrerequisitesRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "product_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliate202402CheckAnchorPrerequisitesRequestBody struct {
	value *Affiliate202402CheckAnchorPrerequisitesRequestBody
	isSet bool
}

func (v NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) Get() *Affiliate202402CheckAnchorPrerequisitesRequestBody {
	return v.value
}

func (v *NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) Set(val *Affiliate202402CheckAnchorPrerequisitesRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliate202402CheckAnchorPrerequisitesRequestBody(val *Affiliate202402CheckAnchorPrerequisitesRequestBody) *NullableAffiliate202402CheckAnchorPrerequisitesRequestBody {
	return &NullableAffiliate202402CheckAnchorPrerequisitesRequestBody{value: val, isSet: true}
}

func (v NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliate202402CheckAnchorPrerequisitesRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


