/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate_seller_v202409

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the AffiliateSeller202409SearchTargetCollaborationsRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &AffiliateSeller202409SearchTargetCollaborationsRequestBody{}

// AffiliateSeller202409SearchTargetCollaborationsRequestBody struct for AffiliateSeller202409SearchTargetCollaborationsRequestBody
type AffiliateSeller202409SearchTargetCollaborationsRequestBody struct {
    // Filtering by target collaborations' status. You can query based on: - ONGOING: If you use ONGOING to search, the remaining validity period of the returned target collaborations will be greater than 7 days. - EXPIRING: If you use EXPIRING to search, the remaining validity period of the returned target collaborations will be less than 7 days. - VALID: If you use VALID to search, all returned target collaborations will be valid. - CANCELING: If you use CANCELING to search, all returned target collaborations will be in the process of canceling. - COMPLETED: If you use COMPLETED to search, all returned target collaborations will be in the state of completed, including expired and canceled.
    CollaborationStatus *string `json:"collaboration_status,omitempty"`
    // Filtering by acceptance status of creators who are invited to target collaborations. You can query based on: - \"ACCEPT\", it means creators have already added the products to the showcase - \"ALL\"\"\", it means regardless of whether the creator adds the product to the Showcase. By default, the target collaborations will be searched by \"ALL\" status.
    CreatorAcceptStatus *string `json:"creator_accept_status,omitempty"`
    // Creators' TikTok User ID.  - CREATOR_ID: If you use CREATOR_ID  to search, you can search for target collaboration information for a specified creator ID.
    CreatorUserId *string `json:"creator_user_id,omitempty"`
    // Filtering by target collaborations' free sample setting. You can query based on: - \"WITH_FREE_SAMPLE\" - \"ALL\" By default, the target collaborations will be searched by \"ALL\" setting.
    FreeSampleSetting *string `json:"free_sample_setting,omitempty"`
    SearchParam *AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam `json:"search_param,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _AffiliateSeller202409SearchTargetCollaborationsRequestBody AffiliateSeller202409SearchTargetCollaborationsRequestBody

// NewAffiliateSeller202409SearchTargetCollaborationsRequestBody instantiates a new AffiliateSeller202409SearchTargetCollaborationsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateSeller202409SearchTargetCollaborationsRequestBody() *AffiliateSeller202409SearchTargetCollaborationsRequestBody {
    this := AffiliateSeller202409SearchTargetCollaborationsRequestBody{}
    return &this
}

// NewAffiliateSeller202409SearchTargetCollaborationsRequestBodyWithDefaults instantiates a new AffiliateSeller202409SearchTargetCollaborationsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateSeller202409SearchTargetCollaborationsRequestBodyWithDefaults() *AffiliateSeller202409SearchTargetCollaborationsRequestBody {
    this := AffiliateSeller202409SearchTargetCollaborationsRequestBody{}
    return &this
}

// GetCollaborationStatus returns the CollaborationStatus field value if set, zero value otherwise.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCollaborationStatus() string {
    if o == nil || utils.IsNil(o.CollaborationStatus) {
        var ret string
        return ret
    }
    return *o.CollaborationStatus
}

// GetCollaborationStatusOk returns a tuple with the CollaborationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCollaborationStatusOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CollaborationStatus) {
        return nil, false
    }
    return o.CollaborationStatus, true
}

// HasCollaborationStatus returns a boolean if a field has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) HasCollaborationStatus() bool {
    if o != nil && !utils.IsNil(o.CollaborationStatus) {
        return true
    }

    return false
}

// SetCollaborationStatus gets a reference to the given string and assigns it to the CollaborationStatus field.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) SetCollaborationStatus(v string) {
    o.CollaborationStatus = &v
}

// GetCreatorAcceptStatus returns the CreatorAcceptStatus field value if set, zero value otherwise.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCreatorAcceptStatus() string {
    if o == nil || utils.IsNil(o.CreatorAcceptStatus) {
        var ret string
        return ret
    }
    return *o.CreatorAcceptStatus
}

// GetCreatorAcceptStatusOk returns a tuple with the CreatorAcceptStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCreatorAcceptStatusOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CreatorAcceptStatus) {
        return nil, false
    }
    return o.CreatorAcceptStatus, true
}

// HasCreatorAcceptStatus returns a boolean if a field has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) HasCreatorAcceptStatus() bool {
    if o != nil && !utils.IsNil(o.CreatorAcceptStatus) {
        return true
    }

    return false
}

// SetCreatorAcceptStatus gets a reference to the given string and assigns it to the CreatorAcceptStatus field.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) SetCreatorAcceptStatus(v string) {
    o.CreatorAcceptStatus = &v
}

// GetCreatorUserId returns the CreatorUserId field value if set, zero value otherwise.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCreatorUserId() string {
    if o == nil || utils.IsNil(o.CreatorUserId) {
        var ret string
        return ret
    }
    return *o.CreatorUserId
}

// GetCreatorUserIdOk returns a tuple with the CreatorUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetCreatorUserIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CreatorUserId) {
        return nil, false
    }
    return o.CreatorUserId, true
}

// HasCreatorUserId returns a boolean if a field has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) HasCreatorUserId() bool {
    if o != nil && !utils.IsNil(o.CreatorUserId) {
        return true
    }

    return false
}

// SetCreatorUserId gets a reference to the given string and assigns it to the CreatorUserId field.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) SetCreatorUserId(v string) {
    o.CreatorUserId = &v
}

// GetFreeSampleSetting returns the FreeSampleSetting field value if set, zero value otherwise.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetFreeSampleSetting() string {
    if o == nil || utils.IsNil(o.FreeSampleSetting) {
        var ret string
        return ret
    }
    return *o.FreeSampleSetting
}

// GetFreeSampleSettingOk returns a tuple with the FreeSampleSetting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetFreeSampleSettingOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FreeSampleSetting) {
        return nil, false
    }
    return o.FreeSampleSetting, true
}

// HasFreeSampleSetting returns a boolean if a field has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) HasFreeSampleSetting() bool {
    if o != nil && !utils.IsNil(o.FreeSampleSetting) {
        return true
    }

    return false
}

// SetFreeSampleSetting gets a reference to the given string and assigns it to the FreeSampleSetting field.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) SetFreeSampleSetting(v string) {
    o.FreeSampleSetting = &v
}

// GetSearchParam returns the SearchParam field value if set, zero value otherwise.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetSearchParam() AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam {
    if o == nil || utils.IsNil(o.SearchParam) {
        var ret AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam
        return ret
    }
    return *o.SearchParam
}

// GetSearchParamOk returns a tuple with the SearchParam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) GetSearchParamOk() (*AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam, bool) {
    if o == nil || utils.IsNil(o.SearchParam) {
        return nil, false
    }
    return o.SearchParam, true
}

// HasSearchParam returns a boolean if a field has been set.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) HasSearchParam() bool {
    if o != nil && !utils.IsNil(o.SearchParam) {
        return true
    }

    return false
}

// SetSearchParam gets a reference to the given AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam and assigns it to the SearchParam field.
func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) SetSearchParam(v AffiliateSeller202409SearchTargetCollaborationsRequestBodySearchParam) {
    o.SearchParam = &v
}

func (o AffiliateSeller202409SearchTargetCollaborationsRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o AffiliateSeller202409SearchTargetCollaborationsRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CollaborationStatus) {
        toSerialize["collaboration_status"] = o.CollaborationStatus
    }
    if !utils.IsNil(o.CreatorAcceptStatus) {
        toSerialize["creator_accept_status"] = o.CreatorAcceptStatus
    }
    if !utils.IsNil(o.CreatorUserId) {
        toSerialize["creator_user_id"] = o.CreatorUserId
    }
    if !utils.IsNil(o.FreeSampleSetting) {
        toSerialize["free_sample_setting"] = o.FreeSampleSetting
    }
    if !utils.IsNil(o.SearchParam) {
        toSerialize["search_param"] = o.SearchParam
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *AffiliateSeller202409SearchTargetCollaborationsRequestBody) UnmarshalJSON(data []byte) (err error) {
    varAffiliateSeller202409SearchTargetCollaborationsRequestBody := _AffiliateSeller202409SearchTargetCollaborationsRequestBody{}

    err = json.Unmarshal(data, &varAffiliateSeller202409SearchTargetCollaborationsRequestBody)

    if err != nil {
        return err
    }

    *o = AffiliateSeller202409SearchTargetCollaborationsRequestBody(varAffiliateSeller202409SearchTargetCollaborationsRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "collaboration_status")
        delete(additionalProperties, "creator_accept_status")
        delete(additionalProperties, "creator_user_id")
        delete(additionalProperties, "free_sample_setting")
        delete(additionalProperties, "search_param")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody struct {
	value *AffiliateSeller202409SearchTargetCollaborationsRequestBody
	isSet bool
}

func (v NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) Get() *AffiliateSeller202409SearchTargetCollaborationsRequestBody {
	return v.value
}

func (v *NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) Set(val *AffiliateSeller202409SearchTargetCollaborationsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateSeller202409SearchTargetCollaborationsRequestBody(val *AffiliateSeller202409SearchTargetCollaborationsRequestBody) *NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody {
	return &NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody{value: val, isSet: true}
}

func (v NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateSeller202409SearchTargetCollaborationsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


